### ISSUE TITLE
I have many namespaces, and I want to create its own events for each namespace. How can I write a separate Listener for each namespace

### ISSUE THREAD

**Issue by diao10** [mrniko/netty-socketio#1005]
I have many namespaces, and I want to create its own events for each namespace. How can I write a separate Listener for each namespace

![image](https://github.com/user-attachments/assets/8127cf3a-db9d-4ff5-ba69-9e881744fa3a)

![image](https://github.com/user-attachments/assets/96bfb962-b658-426e-889c-760370766380)

But I wrote that when the client initiates a request, it will not receive it

![image](https://github.com/user-attachments/assets/0979053b-bfb2-4a24-869b-ea25d99de7f8)

But I can receive it without a comment

![image](https://github.com/user-attachments/assets/474a4deb-e92e-4292-bf2b-3ec55d7d4d1f)

If there are many namespaces, @Onevent does not take effect

Or is there something wrong with what I wrote

Please！！Thank you！

**Comment by diao10** [comment]
It's my problem. I'm looking at the wrong class

**Comment by a151605** [comment]
how? i cant find solution
