### ISSUE TITLE
Don't Support Cross Domain.

### ISSUE THREAD

**Issue by tshi0912** [mrniko/netty-socketio#115]
I've deployed my spring application which contains the netty-socketio server into Server A. Netty is listerning on 9090 port.
And, I'm trying to access the application on another PC B. However it throw below error:

XMLHttpRequest cannot load http://{ip-of-server-a}:9090/socket.io/1/?t=1398080322400. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://{ip-of-server-a}:8080' is therefore not allowed access.

After research for a while, I find it is caused by the cross domain problem. Since netty is listerning on another port, the browser deem the request of http://{ip-of-server-a}:9090/socket.io/1/?t=1398080322400 is crossing the domain http://{ip-of-server-a}:8080, and expected the response with a header Access-Control-Allow-Origin="*" or Access-Control-Allow-Origin="{ip-of-server-a}:8080", but it won't. 

I have searched your code and want to see something about Cross Domain control, unfortunately it don't have. Could you please to add this feature, otherwise I don't think it could be used in a real production env.

**Comment by ipeisong** [comment]
Is there a way to add multi 'Access-Control-Allow-Origin' ?

**Comment by jaydeepTBA** [comment]
please refer my answer 

http://stackoverflow.com/a/34542759/1802348

and comment if you want more detailed information

**Comment by cosmyn9708** [comment]
I'm having the same issue and I can't make it work. This is my socket io server configuration

Configuration conf = new Configuration();
conf.setHostname("localhost");
conf.setPort(1992);
conf.setOrigin("http://WebServerHost:WebServerPort");
final SocketIOServer server = new SocketIOServer(conf);

And in the front end I get this:
VM17141:1 GET http://localhost:1992/trading/?EIO=3&transport=polling&t=MtG8jHl net::ERR_INCOMPLETE_CHUNKED_ENCODING 400 (Bad Request)
(anonymous) @ VM17141:1
h.create @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
u.request @ vue-socketio.js?5132:8
u.doPoll @ vue-socketio.js?5132:8
h.poll @ vue-socketio.js?5132:8
h.doOpen @ vue-socketio.js?5132:8
i.open @ vue-socketio.js?5132:8
h.open @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
l.open.l.connect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
l.reconnect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
i.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
hasXDR.e.onreadystatechange @ vue-socketio.js?5132:8
XMLHttpRequest.send (async)
(anonymous) @ VM17141:1
h.create @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
u.request @ vue-socketio.js?5132:8
u.doPoll @ vue-socketio.js?5132:8
h.poll @ vue-socketio.js?5132:8
h.doOpen @ vue-socketio.js?5132:8
i.open @ vue-socketio.js?5132:8
h.open @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
l.open.l.connect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
l.reconnect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
i.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
hasXDR.e.onreadystatechange @ vue-socketio.js?5132:8
XMLHttpRequest.send (async)
(anonymous) @ VM17141:1
h.create @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
u.request @ vue-socketio.js?5132:8
u.doPoll @ vue-socketio.js?5132:8
h.poll @ vue-socketio.js?5132:8
h.doOpen @ vue-socketio.js?5132:8
i.open @ vue-socketio.js?5132:8
h.open @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
l.open.l.connect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
l.reconnect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
i.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
hasXDR.e.onreadystatechange @ vue-socketio.js?5132:8
XMLHttpRequest.send (async)
(anonymous) @ VM17141:1
h.create @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
u.request @ vue-socketio.js?5132:8
u.doPoll @ vue-socketio.js?5132:8
h.poll @ vue-socketio.js?5132:8
h.doOpen @ vue-socketio.js?5132:8
i.open @ vue-socketio.js?5132:8
h.open @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
l.open.l.connect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
l.reconnect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
i.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
hasXDR.e.onreadystatechange @ vue-socketio.js?5132:8
XMLHttpRequest.send (async)
(anonymous) @ VM17141:1
h.create @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
u.request @ vue-socketio.js?5132:8
u.doPoll @ vue-socketio.js?5132:8
h.poll @ vue-socketio.js?5132:8
h.doOpen @ vue-socketio.js?5132:8
i.open @ vue-socketio.js?5132:8
h.open @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
l.open.l.connect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
l.reconnect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
i.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
hasXDR.e.onreadystatechange @ vue-socketio.js?5132:8
XMLHttpRequest.send (async)
(anonymous) @ VM17141:1
h.create @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
u.request @ vue-socketio.js?5132:8
u.doPoll @ vue-socketio.js?5132:8
h.poll @ vue-socketio.js?5132:8
h.doOpen @ vue-socketio.js?5132:8
i.open @ vue-socketio.js?5132:8
h.open @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
l.open.l.connect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
l.reconnect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
i.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
hasXDR.e.onreadystatechange @ vue-socketio.js?5132:8
XMLHttpRequest.send (async)
(anonymous) @ VM17141:1
h.create @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
u.request @ vue-socketio.js?5132:8
u.doPoll @ vue-socketio.js?5132:8
h.poll @ vue-socketio.js?5132:8
h.doOpen @ vue-socketio.js?5132:8
i.open @ vue-socketio.js?5132:8
h.open @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
l.open.l.connect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
l.reconnect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
i.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
hasXDR.e.onreadystatechange @ vue-socketio.js?5132:8
XMLHttpRequest.send (async)
(anonymous) @ VM17141:1
h.create @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
u.request @ vue-socketio.js?5132:8
u.doPoll @ vue-socketio.js?5132:8
h.poll @ vue-socketio.js?5132:8
h.doOpen @ vue-socketio.js?5132:8
i.open @ vue-socketio.js?5132:8
h.open @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
l.open.l.connect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
l.reconnect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
i.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
hasXDR.e.onreadystatechange @ vue-socketio.js?5132:8
XMLHttpRequest.send (async)
(anonymous) @ VM17141:1
h.create @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
u.request @ vue-socketio.js?5132:8
u.doPoll @ vue-socketio.js?5132:8
h.poll @ vue-socketio.js?5132:8
h.doOpen @ vue-socketio.js?5132:8
i.open @ vue-socketio.js?5132:8
h.open @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
l.open.l.connect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
l.reconnect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
i.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
hasXDR.e.onreadystatechange @ vue-socketio.js?5132:8
XMLHttpRequest.send (async)
(anonymous) @ VM17141:1
h.create @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
u.request @ vue-socketio.js?5132:8
u.doPoll @ vue-socketio.js?5132:8
h.poll @ vue-socketio.js?5132:8
h.doOpen @ vue-socketio.js?5132:8
i.open @ vue-socketio.js?5132:8
h.open @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
l.open.l.connect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
l.reconnect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
i.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
hasXDR.e.onreadystatechange @ vue-socketio.js?5132:8
XMLHttpRequest.send (async)
(anonymous) @ VM17141:1
h.create @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
u.request @ vue-socketio.js?5132:8
u.doPoll @ vue-socketio.js?5132:8
h.poll @ vue-socketio.js?5132:8
h.doOpen @ vue-socketio.js?5132:8
i.open @ vue-socketio.js?5132:8
h.open @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
h @ vue-socketio.js?5132:8
l.open.l.connect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
l.reconnect @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
i.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
n.emit @ vue-socketio.js?5132:1
h.onError @ vue-socketio.js?5132:8
eval @ vue-socketio.js?5132:8
setTimeout (async)
hasXDR.e.onreadystatechange @ vue-socketio.js?5132:8
localhost/:1 Access to XMLHttpRequest at 'http://localhost:1992/trading/?EIO=3&transport=polling&t=MtG8jHl' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
VM17141:1 GET http://localhost:1992/trading/?EIO=3&transport=polling&t=MtG8jHl net::ERR_INCOMPLETE_CHUNKED_ENCODING 400 (Bad Request)
