### ISSUE TITLE
Problem with adding new EventListener.

### ISSUE THREAD

**Issue by SooLiD** [mrniko/netty-socketio#135]
Hi,
I have a little problem. I can't add new eventListener. When I send on old event (for example : test), it's working fine, but when i change in Client (JS) line : socket.json.emit('test', ..); on : socket.json.emit('test1', ...), it's crashing. On 'test' working fine. Is there a maximum count of events ?

**Comment by panda403** [comment]
add default constructor  in Walutuj can resolve the problem......
