### ISSUE TITLE
ERROR JsonSupportWrapper - Can't write value

### ISSUE THREAD

**Issue by SooLiD** [mrniko/netty-socketio#168]
Hi,

I have a different problem with send callback to my JavaScript client. I'm receiving a message and I want to callback an object of class "Offers" (including fields type of long, String, BigDecimal, boolean and SocketIOClient). Last time when I had problem similar like this I was create default constructor and all have been working fine. I'm sure than object "Offers" is creating complete and correctly. Here is my error message : 

23163 [nioEventLoopGroup-3-4] ERROR com.corundumstudio.socketio.JsonSupportWrapper - Can't write value: [Odpowiedzi.Respond@6cdac2c4]
com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class com.corundumstudio.socketio.store.MemoryStore and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) ) (through reference chain: java.util.ArrayList[0]->Odpowiedzi.Respond["zalacznik"]->Oferty.Oferta["soc"]->com.corundumstudio.socketio.transport.NamespaceClient["baseClient"]->com.corundumstudio.socketio.transport.WebSocketClient["store"])

**Comment by xiaoxinba** [comment]
how do you solve the problem? @SooLiD
