### ISSUE TITLE
How to set the header information 'Access-Control-Allow-Credentials'

### ISSUE THREAD

**Issue by qq277049** [mrniko/netty-socketio#186]
XMLHttpRequest cannot load http://localhost:9092/socket.io/?EIO=3&transport=polling&t=1418283758754-41. Credentials flag is 'true', but the 'Access-Control-Allow-Credentials' header is ''. It must be 'true' to allow credentials.
I'm using Version: 1.7.4

**Comment by mrniko** [comment]
fixed
