### ISSUE TITLE
Sending byte[] to the server

### ISSUE THREAD

**Issue by Eski** [mrniko/netty-socketio#189]
Hi, 

I'm trying to send byte[] from the android device with nkzawa/socket.io-client.java to the server with netty-socketio but i get this error on the server :

[nioEventLoopGroup-3-1] ERROR com.corundumstudio.socketio.JsonSupportWrapper - Can't read value 1: ["stream","com.github.nkzawa.socketio.parser.Packet@414203b8"] for type: class com.corundumstudio.socketio.protocol.Event
com.fasterxml.jackson.core.JsonParseException: Illegal character '.' (code 0x2e) in base64 content

Here my client request with nkzawa/socket.io-client.java : 
Packet<byte[]> packet = new Packet<byte[]>(Parser.BINARY_EVENT);
packet.data = "abc".getBytes(Charset.forName("UTF-8"));
socket.emit("stream", packet);

Here my server event : 
server.addEventListener("stream", byte[].class, new DataListener<byte[]>() {
            @Override
            public void onData(SocketIOClient client, byte[] data, AckRequest ackRequest) {
            	System.out.printf("Data receved");
            }
});

I dont know if i'm doing it right in both side so please correcte me.

**Comment by mrniko** [comment]
Please show a netty-socketio log, you need to switch logging level to TRACE for it.

**Comment by Eski** [comment]
I fix this problem by using Netty Socketio version 1.7.5. I was using the 1.7.4 version.
