### ISSUE TITLE
Question: is there a way to also host a webpage

### ISSUE THREAD

**Issue by lpage30** [mrniko/netty-socketio#192]
We have a need to also host a webpage from our socket io server. 
Is there any way to do this with the existing design?
We can see how we could extend the SocketIOChannelInitializer and WrongUrlHandler to then handle such requests, but wondered if there was some other 'per design' way.

**Comment by mrniko** [comment]
Yes, you can. Try `Configuration.setAllowCustomRequests` but you need to write own http-handler in this case.
