### ISSUE TITLE
Return some indication that the port is already bound

### ISSUE THREAD

**Issue by m-marsella** [mrniko/netty-socketio#197]
The startAsync method doesn't return anything indicating whether the server started successfully or not, nor does it throw an exception.  It does log a message though. Could the ```Future<Void>``` be made a  ```Future<Boolean>``` and return true of false on the if clauses?.

```java
      return b.bind(addr).addListener(new FutureListener<Void>() {
            @Override
            public void operationComplete(Future<Void> future) throws Exception {
                if (future.isSuccess()) {
                    log.info("SocketIO server started at port: {}", configCopy.getPort());
                } else {
                    log.error("SocketIO server start failed at port: {}!", configCopy.getPort());
                }
            }
        });
```

**Comment by mrniko** [comment]
use `isSuccess()` on Future returned by `SocketIOServer.startAsync()` method

**Comment by m-marsella** [comment]
My actually problem was when restarting my service it wouldn't be able to bind, reporting the port was still in use, it had to wait a few minutes.  I solved this by setting setReuseAddress to true on the SocketConfig.  Thanks.

**Comment by pablojr** [comment]
I guess it's a symptom of an improper shutdown...

**Comment by m-marsella** [comment]
No it's by design, TCP has allow for packets to arrive after shutdown so it waits a few minutes before allowing a rebind.  For my purposes though when developing I was restarting a lot so was a pain to wait.
