### ISSUE TITLE
Unescaped \n, \r, " in packet caused "parse error" on client in jsonp mode

### ISSUE THREAD

**Issue by alim-akbashev** [mrniko/netty-socketio#205]

**Comment by mrniko** [comment]
your fix has not been worked with "\n" in string

**Comment by alim-akbashev** [comment]
Weird, works  in our project. I'll recheck in demo project.

**Comment by alim-akbashev** [comment]
yep, found it. in fact it's another half of the issue - NPE on server-side during parse POST of new message. Need to fix PacketDecoder in same manner as PacketEncoder. In progress. new fix will be committed soon :)

**Comment by alim-akbashev** [comment]
oh, sorry, had not noticed that you've already fixed. do you want me to continue the work on this issue? i have another solution, imho, little bit more optimal.

**Comment by mrniko** [comment]
some optimizations, thanks for your help

**Comment by alim-akbashev** [comment]
np
