### ISSUE TITLE
Symbol "," at the end of namespace

### ISSUE THREAD

**Issue by dkorkin** [mrniko/netty-socketio#211]
I have symbol "," at the end of namespace (using client library https://github.com/shuoli84/SocketIOCocoa) maybe I am doing something wrong? But I used same client and worked with node js server-side (https://github.com/Automattic/socket.io) without such problems.  I had to add 

 Packet packet = decoder.decodePackets(content, client);
 packet.setNsp(packet.getNsp().replaceAll(",", ""));

to com.corundumstudio.socketio.handler.InPacketHandler in line 66 Maybe there is no check for special chars?

**Comment by mrniko** [comment]
Can't get it work with `socketio.js 1.3.3 client` and `node socketio.js`. I have an error for `/chat2,23` namespace `?44/chat2,"Invalid namespace"`
