### ISSUE TITLE
Closing connection

### ISSUE THREAD

**Issue by tselishev-semen** [mrniko/netty-socketio#212]
Hi all. I have a problem, when the user connected from another country. Server located in Russia, the client is in Italy. There is a very slow internet.

Сonnection is established( fired 'connect' event), but then stops working.
On the client (in browser) an error 500 (Internal Server Error)
On the netty server
```
 ERROR com.corundumstudio.socketio.transport.PollingTransport - fc041f82-abd8-405b-9012-2ea1c38568b6 is not registered. Closing connection

```
nginx log:
```
2015/02/10 11:25:34 [info] 19760#0: *88 client #.###.##.### closed keepalive connection
```
I use NGINX as a WebSocket Proxy(http://nginx.com/blog/websocket-nginx). I tried to increase the timeouts:
```nginx
    keepalive_timeout 70s
    send_timeout 60s;
    client_body_timeout 72s;
    client_header_timeout 72s;
```
but it did not help:(( 

I need you help

**Comment by tselishev-semen** [comment]
To reproduse error, i'am use slow italian proxy 82.85.8.99:8080.

**Comment by mrniko** [comment]
have you tried to change netty-socketio timeouts?

**Comment by pablojr** [comment]
In order to simulate (under controlled conditions) a slow network connection in your test environment, you may want to take a look at this tool: [Sloppy](http://www.dallaway.com/sloppy/)

**Comment by tselishev-semen** [comment]
> have you tried to change netty-socketio timeouts?

@mrniko, I tried:
```java
       config.setUpgradeTimeout(10000000);
       config.setPingTimeout(10000000);
```
But it did not help

**Comment by mrniko** [comment]
you forgot to set long `pingInterval`

**Comment by tselishev-semen** [comment]
I added
```java 
    config.setUpgradeTimeout(10000000);
        config.setPingTimeout(10000000);
        config.setPingInterval(10000000);
```
It did not help

**Comment by tselishev-semen** [comment]
@pablojr, Thanks, I'll try to use it in the near time

**Comment by piscui** [comment]
Try adding this directive in your nginx's <code>server</code> context:
<code>proxy_read_timeout 86400s;</code>

**Comment by tselishev-semen** [comment]
@piscui, thanks for the idea. I will try to set this option. But now I can not reproduce the bug. I close this issue.

**Comment by blogsit** [comment]
I have a problem ，the same to you ？  solution？

**Comment by blogsit** [comment]
error  message 

ERROR com.corundumstudio.socketio.transport.PollingTransport - 3a129585-34d9-45cb-b82a-cd55365a73fc is not registered. Closing connection

**Comment by piscui** [comment]
In my case it helped tweaking the OS and nginx, not 100% bullet proof but it reduced the error count significantly.

You may need to increase your OS and nginx max open files limit (check your nginx error logs to confirm). Do a `ulimit -n` and increase the value if needed (ie. `ulimit -n 30000`), then add `worker_rlimit_nofile 30000;` to your nginx config.

Also increase the `worker_processes` value to `2 * number of processors/cores` and `worker_connections` to a value close to `worker_rlimit_nofile` (ie. `20000` going by the previous example). Don't forget to reload nginx.

Last but not least, make use you're using the latest version of `socket.io.js`.

I hope it helps.

**Comment by blogsit** [comment]
thanks  @piscui   
Using this  method  “Try adding this directive in your nginx's server context:
proxy_read_timeout 86400s;”  Solved the problem,  because   nginx  timeout set  3s .  Using 
this nginx config Solved the problem.
 location /epush {
                proxy_pass http://epush_socket;
                proxy_buffering    off;
                proxy_read_timeout 30s;
        }

**Comment by tselishev-semen** [comment]
In the clien side(http://socket.io/docs/client-api/) has the option of <b>timeout</b>
```js
io.connect(connectUrl, {reconnectionDelay: 3000, timeout: 15000})
```
I do not know what helped me, but I think it can also help
