### ISSUE TITLE
Cannot Switch JsonSupport implementation

### ISSUE THREAD

**Issue by niffrig** [mrniko/netty-socketio#213]
It is impossible to switch JSON support implementation cleanly if you do not bring Jackson libraries along.  I'm attempting to use a GSON implementation of that interface because of classpath issues with Jackson.  However constructing Configuration causes classpath errors to be thrown before we have a chance to switch out the JsonSupport implementation.

**Comment by hiddenmin** [comment]
+1

**Comment by mrniko** [comment]
fixed
