### ISSUE TITLE
JSONP polling support

### ISSUE THREAD

**Issue by gding8** [mrniko/netty-socketio#217]
Hi, we have to support some very old IE versions that will initiate JSONP-polling instead of XHR-polling. Do you think we can write our own JSONP-polling handler, hook it up with the netty pipeline and make it to work? Thanks.

**Comment by mrniko** [comment]
> JSONP-polling handler
JSONP-polling already implemented. Why do you need to write own version?

**Comment by gding8** [comment]
Thanks for the prompt reply. I thought you only implemented websocket and xhr-polling as listed under the "Features" section of this wiki page. In our testing, if it is IE7 and lower, the socket.io client failed to establish a connection. Did we miss something?

**Comment by mrniko** [comment]
it switches to jsonp in ie9... is it work good with native nodejs version of socketio server?

**Comment by gding8** [comment]
I see. I got the same result when testing against a nodejs socket.io server and it didn't work with IE7 and lower. Now I am thinking maybe I used some features in my client and those were not supported in IE7. Did you ever test IE7 and even lower IE versions? Thanks a lot.

**Comment by pablojr** [comment]
@gding8 I have an application using netty-socketio working with IE6 given that you install Flash in the browser, so the transport is flashsocket

**Comment by gding8** [comment]
@pablojr Interesting! I read IE doesn't support websocket until IE10. So with flashsocket, is the websocket protocol actually implemented in the flash objects (SWF files)?

**Comment by mrniko** [comment]
@gding8 i think @pablojr talking about old version of netty-socketio 1.6.x not 1.7.x. New socketio client has dropped flash-transport support

**Comment by pablojr** [comment]
@gding8 yes, @mrniko is right  I keep using an old version (1,x?) which contains the required SWF files to support flashsocket. So you need to provide Flash player for that code to work properly. I'm away for actual code, I can reply better next week. You may want to take a look at old revisions of this project

**Comment by gding8** [comment]
Thanks guys. I reran my test using netty-socketio 1.7.3 and socket.io-1.3.4.js, I couldn't even get IE9 to work. The same client code works fine against a nodejs server down through IE8. According to the sniffer trace, the netty-socketio server definitely didn't send any data to the client although the handshake seemed being completed OK. On the server machine, I could see a TCP socket connection established and a couple of other connections were flapping. I think that's how polling mode is supposed to work if I understand it right.

I have such a simple test client (see below). What is wrong?

<script>  
  var socket = io.connect('http://192.168.25.55:12007?action=subscribe');
  socket.on('message', function(msg){
     $('#messages').append($('<li>').text(JSON.stringify(msg)));
  });
</script>

**Comment by gding8** [comment]
Update: we switched to latest release (netty-socketio 1.7.7) and the client in IE8 worked. Something must have been fixed since 1.7.3.
