### ISSUE TITLE
Hazelcast Nodes

### ISSUE THREAD

**Issue by KSfrancis** [mrniko/netty-socketio#219]
Good Day! 

I have a cluster of hazelcast instances running along side socket.io for my game servers behind nginx. The logs show sessions joining and leaving on all four game servers. However, a server cant seem to send a message to clients connected to a different server.

I'm using storefactory and getClient, does the client array sync with all servers by default or should I implement my own pubsub like http://hazelcast.org/use-cases/messaging/ ?

Thanks in advance!

**Comment by KSfrancis** [comment]
Finally got it working by storing ser

**Comment by mrniko** [comment]
@KSfrancis by what?

**Comment by KSfrancis** [comment]
Sorry for the wrong post. I currently got it working with this setup:

-> on connection, stored the name of the server (in which the client is connected to) in the session store.
-> created an executorservice for executing a distributed task for sending socketio messages.
-> the above task will be executed on the hazelcast cluster member with the name equal to the player's servername in its session store.

**Comment by mrniko** [comment]
Could you publish this code?
