### ISSUE TITLE
how to implement the distribute session with pure jedis

### ISSUE THREAD

**Issue by chembohuang** [mrniko/netty-socketio#227]
Hi, mrniko:
      We have been using this amazing project as our communication framework. And now we want to make a horizontal expansion and hope to share the sessions across the distribute nodes. We already know that the project has implemented this function with hazelcast and redisson. Though we use redis, we can't use the redisson as we have our own jedis base failover framework, so we decide to implement the pub/sub session ourself.  If i wasn't wrong, there are 3 files we need to implement with: JedisStore JedisStoreFactory and JedisPubsubStore, Here is what we have done:
     JedisStore and JedisStoreFactory are easy to be done. We stuck in the JedisPubSubStore.subscribe method, we don't konw how to overide it since the jedis sub/pub is blocking(doesn't have the callback method) and jedis doesn't have sth. like getTopic and so on.
     Hope you could help us out. Million thanks.

**Comment by mrniko** [comment]
Hi! Thanks for good words about this project!

> since the jedis sub/pub is blocking
Have you tried to run it in another thread?
