### ISSUE TITLE
SSL Performance

### ISSUE THREAD

**Issue by lpage30** [mrniko/netty-socketio#234]
Hi,
We are running with TLS and we can only connect up to 150 secure polling clients for 15 min
and the server's cpu gets pegged.... We have no issue with 2k+ non polling clients (10% of 4 cpus only).

So we have been trying to figure out how to 'reuse' the session as we attribute the high latency and hit with the polling clients having to re-initiate their session EVERY time.

We have tried setting the session timeout and cachesize on the sslcontext before generating the sslengine, but that had no effect.
We had investigated native solutions (finagle or netty's own open ssl) with no real success.

How can we (either by client or server) have the polling clients 'reuse' their session when they poll?

Thanks.

**Comment by mrniko** [comment]
have you tried this setup: nginx with ssl + netty-socketio behind?
