### ISSUE TITLE
How to store the SocketIOClient with redisson?

### ISSUE THREAD

**Issue by fengzhiqiu** [mrniko/netty-socketio#236]
Hello , mrniko . I saw that this project has supported client store with Redisson , I want to known that the "store" means  what ? If i can store the client in the redis directly or only store the client sessionid in redis ? These days i try to store SocketIOClient in the redis directly , but the SocketIOClient dosn't implements the Serializable interface , so when i want to store the client in redis , it always failed . How can i store the SocketIOClient in redis ? Could please help me ?

**Comment by mrniko** [comment]
Hi! you should not store SocketIOClient in any storage, because this is a stateful object it has a network connection and etc.
