### ISSUE TITLE
Access-Control-Allow-Credentials in 1.6.x

### ISSUE THREAD

**Issue by demmys** [mrniko/netty-socketio#238]
Hi,
I am using 1.6.7 and want to use the socket.io via cross domain.
I tried `setOrigin` option in the `Configuration` class, but socket.io client browser printed out the error like below.
```
XMLHttpRequest cannot load http://localhost:8080/socket.io/1/?t=1432609638721. Credentials flag is 'true', but the 'Access-Control-Allow-Credentials' header is ''. It must be 'true' to allow credentials.
```

I think it is the same problem as https://github.com/mrniko/netty-socketio/issues/186,  but this fix had not been merged into the branch "1.6" yet.

Is there any plan to merge that fix into the branch "1.6"?

**Comment by mrniko** [comment]
fixed
