### ISSUE TITLE
socketio server get empty json from nodejs cleint. 

### ISSUE THREAD

**Issue by BaichaoLi** [mrniko/netty-socketio#243]
Server side code:

        server.addEventListener("eventname", JSONObject.class, new DataListener<JSONObject>() {
            @Override
            public void onData(SocketIOClient client, JSONObject data, AckRequest ackRequest) {
            	System.out.println("JSON Got1");
            	System.out.println(data.toString());
            }
        });

Client side code:

  var socket = require('socket.io-client')('http://192.168.198.153:20000');
  var msg = {
          mn : 'request_message',
          code : 200,
          body : {
                  msg : 'this is msg from request',
          }
  }
  socket.on('connect', function(){});
  socket.emit('videbouds10', msg);
  socket.on('disconnect', function(){});

Result:

JSON Got1
{}

I debugged that , it seems that the Json parser dosen't get json object out.  could you please have a look at the problem?

**Comment by 380099106** [comment]
eventname? is wrong....

**Comment by BaichaoLi** [comment]
the event name actually is "videbouds10" , I changed when I pasted. sorry for that. 

socket.on('connect', function(){});
socket.emit('eventname', msg);
socket.on('disconnect', function(){});

Result:

JSON Got1
{}

**Comment by mrniko** [comment]
What is `JSONObject` this object can't be used with Jackson-codec used by default. To use `JSONObject` object you should implement your own `JsonSupport` provider and set it via `Configuration.setJsonSupport`
