### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by qzc77** [mrniko/netty-socketio#246]
sockectio4Net client request server
http://localhost:9092/socket.io/，response 401 unauthorized,why?

**Comment by mrniko** [comment]
Try 1.6.7 version of netty-socketio

**Comment by qzc77** [comment]
but java socket.io client  is Normal

**Comment by qzc77** [comment]
http://socketio4net.codeplex.com/
debug ：
socketclient.conect(), step into handshake throw exception，401 Unauthorized

**Comment by mrniko** [comment]
> but java socket.io client is Normal
if so then the problem is in socketio4net lib
