### ISSUE TITLE
"Address already in use" when restarting server

### ISSUE THREAD

**Issue by NachoSoto** [mrniko/netty-socketio#254]
I'm not sure if I'm doing something wrong, but I always need to wait for a few seconds before starting the server again, or else I'll get a `java.net.BindException` with this error.

I actually have this to ensure that `stop` is always called:
```java
Runtime.getRuntime().addShutdownHook(new Thread(server::stop));
```

But somehow that's not freeing the port.
`netstat -anp tcp | grep 3001` does not show anything, however, so I'm not sure why `netty-socketio` fails to bind to the port.

**Comment by 380099106** [comment]
The port state is CLOSE_WAIT?

**Comment by NachoSoto** [comment]
@380099106 what do you mean?

**Comment by SerCeMan** [comment]
REUSE_PORT solve your problem, try this code when you start server
```kotlin
  val config = Configuration()
  config.setHostname("localhost")
  config.setPort(port)
  val sockConfig = SocketConfig()
  sockConfig.setReuseAddress(true)
  config.setSocketConfig(sockConfig)
  val server = SocketIOServer(config)
```

**Comment by NachoSoto** [comment]
Thanks! I thought this was not public API since it's not documented.

**Comment by pablojr** [comment]
@NachoSoto you are more than welcomed to update the documentation now that you have learnt something new about this excellent project. Don miss your opportunity!

**Comment by JiaoMing** [comment]
@SerCeMan  Thanks

**Comment by bamossza** [comment]
@SerCeMan Thank you.

**Comment by devpage** [comment]
@SerCeMan Good :)

**Comment by hedefu999** [comment]
> REUSE_PORT solves your problem, try this code when you start server
> 
> ```kotlin
>   val config = Configuration()
>   config.setPort(port)
>   val sockConfig = SocketConfig()
>   sockConfig.setReuseAddress(true)
>   config.setSocketConfig(sockConfig)
>   val server = SocketIOServer(config)
> ```

thanks, that fixes an annoying problem in my project

**Comment by heja1600** [comment]
That actually doesnt solve this for me, i use the following code: 
`**        Configuration config = new Configuration();
        config.setOrigin("*");
        config.setHostname("localhost");
        config.setPort(PORT);
        SocketConfig socketConfig = new SocketConfig();
        socketConfig.setReuseAddress(true);
        config.setSocketConfig(socketConfig);

        server = new SocketIOServer(config);
        server.addConnectListener(this);
        server.addDisconnectListener(this);
        server.start();**`


and get the following stacktrace: 

`[INFO] [ERROR   ] SRVE0271E: Uncaught init() exception created by servlet [InitServlet] in application [SnickeboServer]: java.net.BindException: Address already in use: bind
[INFO]  at java.base/sun.nio.ch.Net.bind0(Native Method)
[INFO]  at java.base/sun.nio.ch.Net.bind(Net.java:479)
[INFO]  at java.base/sun.nio.ch.Net.bind(Net.java:468)
[INFO]  at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
[INFO]  at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
[INFO]  at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:550)
[INFO]  at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
[INFO]  at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:504)
[INFO]  at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:489)
[INFO]  at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
[INFO]  at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:248)
[INFO]  at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:348)
[INFO]  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[INFO]  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[INFO]  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[INFO]  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[INFO]  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[INFO]  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[INFO]  at java.base/java.lang.Thread.run(Thread.java:832)
`
