### ISSUE TITLE
C＃ client

### ISSUE THREAD

**Issue by qzc77** [mrniko/netty-socketio#257]
Please recommend a.Net client, server is 1.6.6, and now with https://github.com/Quobject/SocketIoClientDotNet/, emit, parsing data exception

**Comment by mrniko** [comment]
sorry but i have not used a .net client

**Comment by qzc77** [comment]
thanks，I'll think about it.

**Comment by WestFive** [comment]
Try to change the connect way 
before  http://server.url:port 
after    ws://server.url.port 

i used this way
