### ISSUE TITLE
how to pass auth_token

### ISSUE THREAD

**Issue by arisAlexis** [mrniko/netty-socketio#259]
I would like to pass a query string as some people do with the js version like:

var socket =  io.connect('http://localhost:8444',{ query: 'token=12345' });

but I cannot find this string anywhere in the SocketIOClient that is passed to the ConnectListener. 

how can I implement this? I want to check the database and only if valid then I open the connection otherwise I reject it.

**Comment by mrniko** [comment]
Use `Configuration.authorizationListener`

**Comment by arisAlexis** [comment]
Yes I was looking into that but how can I get the query token? It is not in the handshake data object.

**Comment by mrniko** [comment]
it's stored as query param, right?

**Comment by arisAlexis** [comment]
ah it is in the urlParams of the handshake data. thank you

**Comment by gurmeetb** [comment]
@mrniko  I am using `1.7.16`, but I don't see the query I am passing in urlParams of the handshake data - any idea if it is still supported ?

`io.connect(chat1SocketUrl, { query: 'token=12345' });` -  this is what I tried on client side.
