### ISSUE TITLE
Redisson store doesn't work in version 1.7.7

### ISSUE THREAD

**Issue by fcbflying** [mrniko/netty-socketio#260]
In version 1.7.7, I try to use RedissonStore, but it doesn't work while it works well in version 1.6.7.
I find from the source code, some code store the HandshakeData into redis in the AuthorizeHandler was removed from  version 1.7.7. 

What need to do in version 1.7.7 if I want to store  something into redis with Redisson, for example HandshakeData?

Also I found the default store way is MemoryStore, but the method createMap in store factory is never called anywhere, which confused me.
Could you give me some help?
Thanks.

**Comment by mrniko** [comment]
The HandshakeData now stores in `com.corundumstudio.socketio.handler.ClientHead` object. So storing in memoryStore is not needed anymore

**Comment by fcbflying** [comment]
And for the whole StoreFactory(RedissonStore, HazelcastStore, MemoryStore) module will not needed anymore? Because I don't find anywhere to store data with them or get data from them.

Thanks.

**Comment by mrniko** [comment]
`createStore` and `pubSubStore` are still in use

**Comment by mrniko** [comment]
@fcbflying Did you resove the problem?
