### ISSUE TITLE
Event objects and json objects What is the difference

### ISSUE THREAD

**Issue by 178620086** [mrniko/netty-socketio#261]
like this 

<pre>

                // send json-object to server
                // '@class' property should be defined and should 
                // equals to full class name.
                var obj = { '@class' : 'com.sample.SomeClass',
                             ...
                          };
                socket.json.send(obj);

                // send event-object to server
                // '@class' property is NOT necessary in this case
                var event = { 
                             ...
                          };
                socket.emit('someevent', event);

</pre>

**Comment by mrniko** [comment]
oh, this api example for old socketio client prior 1.x.x version. Since 1.0.0 version only events allowed

**Comment by 178620086** [comment]
thank you 
do you know this project 
https://code.google.com/p/socketio-netty/

**Comment by mrniko** [comment]
@178620086 Yes. I saw it before.
