### ISSUE TITLE
socket.io  LINUX TCP

### ISSUE THREAD

**Issue by c8439** [mrniko/netty-socketio#263]
![t03v3t m oens a fr5hppj](https://cloud.githubusercontent.com/assets/13691096/9131263/b2f584e2-3d1c-11e5-9726-d25c0ab884a3.jpg)
Client connects to the SOCKET.IO, on-line users, due to the instability of the user network signal, dropped the, and Linux system the user TCP did not release out, the user to connect again socket.io Linux system in adding a TCP.

![t03v3t m oens a fr5hppj](https://cloud.githubusercontent.com/assets/13691096/9131263/b2f584e2-3d1c-11e5-9726-d25c0ab884a3.jpg)

**Comment by mrniko** [comment]
and connections are established forever? if so it's not possible due to tcp protocol spec

**Comment by c8439** [comment]
![7 syucl3l 32 cuupa6f3u6](https://cloud.githubusercontent.com/assets/13691096/9131794/56f3a2be-3d21-11e5-8ee1-5585e5310a06.jpg)
Online users only hundreds of TCP, there were more than 5000, but also continue to add, established

**Comment by mrniko** [comment]
which transport do you use? if xhr-polling then it's normal

**Comment by c8439** [comment]
The server is socket.io1.6.6; client is socket.io https://github.com/socketio/socket.io-client-swift

**Comment by c8439** [comment]
How to release the TCP server, client dropped

**Comment by c8439** [comment]
Customer service side no network, disconnect, waiting for a while, the server is disconnected from the customer service side, but established TCP can not be released, the customer service side again, TCP again to add a. There is no way to release the TCP established.

**Comment by ryandietrich** [comment]
I would suggest looking into your TCP settings for your system, specifically:

net.ipv4.tcp_fin_timeout
net.ipv4.tcp_tw_reuse
net.ipv4.tcp_syn_retries
net.ipv4.tcp_synack_retries
net.core.somaxconn
net.core.netdev_max_backlog

**Comment by liyang1025** [comment]
@mrniko  hi why don't  consider  the server ping  and the client  pong if the client is droped   the server  detect the client is disconnect. server close the socket. ranther than  adjust the system config.

**Comment by mrniko** [comment]
@liyang1025 ping/pong mechanics already implemented in socketio protocol. And there is `pingtimeout = pingTimeout + pingInterval` parameter used in that case

**Comment by liyang1025** [comment]
yes  i also  find the  api about ping timeout  ping  interval，but  it is not  close the  socket channel   my Colleague  update    schedulePingTimeout  function    and  add the statement  get channel from the client  
and then close the channel .so  the  tcp socket  is close !   is't right?

**Comment by su986** [comment]
@liyang1025. i am also facing similar issue.
i am doing security test for the Socket IO ports. As part of this I am creating huge traffic/flood on the port. Then, after completion of the traffic, verifying the port status. 2-3 hours the connections keep on established even though flood stopped.since we have WAN network, pingtimeout won't work for us.
any other suggestion/solution?

**Comment by mrniko** [comment]
@liyang1025 could make a pull request?

**Comment by cheryc** [comment]
TransportState state = channels.get(Transport.WEBSOCKET);
state.getChannel().close();

**Comment by mrniko** [comment]
@yanghongge you don't need to do that now. Because i fixed it in last commit.

**Comment by mrniko** [comment]
guys, please recheck this issue with build from `master` branch
