### ISSUE TITLE
Use netty-socketio in Spring Boot

### ISSUE THREAD

**Issue by maksimu** [mrniko/netty-socketio#267]
I'm using spring boot for some of my projects. So far Netty-socketio works great besides Tomcat, where Tomcat uses port 8080 and netty-socketio uses port 9000. Is it possible to somehow put them both on to the same port where netty-socketio be on 8080 along with Tomcat?

I know Netty and Tomcat are two different servers but maybe there is a way to marry them together?

**Comment by mrniko** [comment]
Hi! I think it's hard to do this because of difference in protocols: socketio uses low-level network layer but tomcat uses servlets. To integrate them together you can write a servlet, i think.

**Comment by Aftabnack** [comment]
Hi,

Any pointers towards that?
I mean porting this to tomcat.
