### ISSUE TITLE
Not getting any data in second object of OnDate

### ISSUE THREAD

**Issue by ca-mcknight** [mrniko/netty-socketio#271]
When I use  and OnEvent handler like this:
`@OnEvent("Login")
     public void onLoginHandler(SocketIOClient client, JSONObject data, AckRequest ackRequest) {
         System.out.println("Incoming Login: "+data);
         client.sendEvent("LoginResponse", loginResponse);
     }`

the 'data' for all events is empty, for every event I have tried. 
When I change the JSONObject to a String, I get the error:

`ERROR com.corundumstudio.socketio.JsonSupportWrapper - Can't read value: ["Login",{"Domain":"test","UserName":"test05","Password":"Password"}] for type: class com.corundumstudio.socketio.protocol.Event
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: io.netty.buffer.ByteBufInputStream@1998ea4e; line: 1, column: 9]`

containing all of the data I expected to be in the data Json object in the second argument of the of that array. 

The client log has the message:
event: Login, data: {"Domain":"test","UserName":"test05","Password":"Password"}

I did not have access to the client code, so that is pretty much all I have to go on from that side.
I do know it is using websockets, but that is the only other detail I am aware of from the client side.

Is there something I am missing in my implementation, or is there something wrong on the client end that I need to raise a ticket for?

Thanks

**Comment by Dmunch04** [comment]
Did you find a fix? I have a similar problem

**Comment by ca-mcknight** [comment]
This was 4 years ago, on a project I got about 1/2 of the way throw then got scrapped. 
I honestly do not think I fixed it before it got scrapped, forgot I even had this open honestly.

**Comment by Dmunch04** [comment]
Oh I see. Fair enough. Well I actually fixed it by using `Map` as my class instead of a custom class. So yeah.
