### ISSUE TITLE
netty-socketio-1.7.7 not support flashsocket transport？

### ISSUE THREAD

**Issue by junping1986** [mrniko/netty-socketio#280]
Configuration details say config.setTransports(Transpot... transports) will set Transports supported by server;Such as:
setTransports Transports supported by server, defaults to [Transport.WEBSOCKET, Transport.FLASHSOCKET, Transport.XHRPOLLING]. Cannot be empty list
But enum Transport only has WEBSOCKET and POLLING,and Project netty-socketio-demo client example flashsocket-index.html，connet to server say 
var socket =  io.connect('http://localhost:9092', {'transports': ['flashsocket']});
This example is not running at all.
Can you tell me how to slove it, or do I understand it?Thanks！

**Comment by mrniko** [comment]
oh, it seems like I forgot to delete flashsocket-index.html. Starting from 1.x version of socketio protocol flashsocket has been dropped.

**Comment by junping1986** [comment]
Thank you!I‘ve just found this in version 1.7.0 released。
