### ISSUE TITLE
addMessageListener not there anymore? Alternative?

### ISSUE THREAD

**Issue by a-reisberg** [mrniko/netty-socketio#283]
It seems like server.addMessageListener() doesn't exist anymore even though it's on the readme. How does one capture messages sent from socket.io via socket.send()?

There's a method called server.addListeners whose argument is just an object. Is it somehow related to the question above? What is this method for and how does one use it?

Thanks a lot!
Alex

**Comment by mrniko** [comment]
`socket.send()` sends an event, so use addEventListener() method to capture it. Use server.addListeners to register object listeners with socketio annotations.

**Comment by a-reisberg** [comment]
Thanks for your reply. So `server.addMessageListener()` indeed disappeared?

In contrast to `socket.emit()`, `socket.send()` doesn't have an `EventName` (it just sends a string to the server). So, if I use `addEventListener`, what `EventName` should I put in? The signature of `socket.send()` seems to match that of `server.addMessageListener()` instead.

**Comment by mrniko** [comment]
> In contrast to socket.emit(), socket.send() doesn't have an EventName

**Comment by a-reisberg** [comment]
I think they have this `socket.send()` pretty much from the beginning (the socket.io.js that you include in your demo definitely has this). You can take a look, for example, at the bottom of the page http://socket.io/docs/

Maybe the `EventName` is now `"message"`?

Thanks.

**Comment by a-reisberg** [comment]
`"message"` is indeed the right event name. It would be great if you could remove `server.addMessageListener` from the readme since it doesn't exist anymore.

Thanks.

**Comment by mrniko** [comment]
@a-reisberg will do!

**Comment by a-reisberg** [comment]
Awesome! Thanks.
