### ISSUE TITLE
How to  support   FlashSocket?

### ISSUE THREAD

**Issue by majintao** [mrniko/netty-socketio#285]
I try to use flash socket,like    config.setTransports(Transport.FLASHSOCKET);

But  i didnt support yeah!

I use this version:
 <dependency>
      <groupId>com.corundumstudio.socketio</groupId>
      <artifactId>netty-socketio</artifactId>
      <version>1.7.8</version>
  </dependency>

**Comment by mrniko** [comment]
FLASHSOCKET transport has been dropped since 1.7.0 version
