### ISSUE TITLE
Did not  find the method  "addJsonObjectListener"

### ISSUE THREAD

**Issue by majintao** [mrniko/netty-socketio#298]
![Uploading 69AC5502-D648-4C3B-AA11-23A0D22D3C87.png…]()

**Comment by majintao** [comment]
![69ac5502-d648-4c3b-aa11-23a0d22d3c87](https://cloud.githubusercontent.com/assets/5277825/11912221/898153f0-a66e-11e5-8a1b-eefc2a10e310.png)

**Comment by mrniko** [comment]
Please use `addEventListener` method
