### ISSUE TITLE
Did  anyone know how to build a distributed chatroom with netty-socketio?

### ISSUE THREAD

**Issue by majintao** [mrniko/netty-socketio#299]
Give me some article or advices!   Thank you!

**Comment by sumory** [comment]
@majintao 
- use netty-socketio to hold connections between clients and server
- scale out servers with MQ

this project([Gru](https://github.com/sumory/gru)) may be a good example for you.

**Comment by majintao** [comment]
Thank you! I saw it before!    I think  (Gru) the private chat messge will post to all the server!   So i want to try other example !

**Comment by majintao** [comment]
Do you have api doc for netty-socketio?  It is hard to learn because of the little wiki comments!!

**Comment by mrniko** [comment]
@majintao There is no api docs, sorry. Don't have time for it.

**Comment by majintao** [comment]
OK！
