### ISSUE TITLE
HeartBeat Config Question!

### ISSUE THREAD

**Issue by majintao** [mrniko/netty-socketio#307]
setHeartbeatInterval Heartbeat interval (in seconds), defaults to 25
setHeartbeatTimeout Heartbeat timeout (in seconds), defaults to 60. Use 0 to disable it
setCloseTimeout Channel close timeout (in seconds) due to inactivity, defaults to 60

It means that the server send the heartbeat package or  the client send ?
If the server send it, it may slowing down performance？？？

**Comment by mrniko** [comment]
> It means that the server send the heartbeat package or the client send ?

Client sends `PING` and server replies `PONG`.

> If the server send it, it may slowing down performance？？？

Not really.

**Comment by majintao** [comment]
https://searchcode.com/codesearch/view/17317840/

The server send   and   wait for the replie!
