### ISSUE TITLE
Block wrong request!

### ISSUE THREAD

**Issue by whutchtwo** [mrniko/netty-socketio#309]
Hi,

Currently netty-socketio is working fine for me pushing data (although temporarily using long polling).
However, I am getting the following warning from netty-socketio excessively.
WARN  [com.corundumstudio.socketio.handler.AuthorizeHandler] Blocked wrong request! url: /, ip: /XX.XX.X.XX:40285

I am using:
socketio client 1.3.6
netty-socketio 1.7.7 (running in jboss)

This is my apache configuration:
RewriteRule ^/socket.io/ http://127.0.0.1:9092/socket.io/$1 [P]
ProxyPassReverse /socket.io/ http://127.0.0.1:9092/socket.io/

I am seeing these warnings on our QA and production machines. I am not seeing the warning locally when I use the same configuration.
Any ideas what may be causing this?

Thanks,
Hutch

**Comment by mrniko** [comment]
Someone trying to connect via wrong url or url not used by socketio protocol.

**Comment by whutchtwo** [comment]
Thank you.
This is the format I am sending sending from the client. Does it look correct?
https://xxx.xxx.xx.xxxxx/socket.io/?EIO=3&transport=polling&t=L95xzyD

**Comment by mrniko** [comment]
@whutchtwo yep

**Comment by whutchtwo** [comment]
So it appears that network monitoring accesses that port every 10 seconds. I had temporarily changed log4j.properties to ERROR level logging, but wanted to provide networking a path to use that would not cause excessive warn logging. Not sure if this was the best approach, but this is what I ended up doing.

config.setAllowCustomRequests(true); 
By allowing custom requests the piece of code displaying the warning was bypassed in Authorizehandler.

I created a custom pipeline, that allowed me to switch out the wrongUrlHandler with a custom one to allow a safe path to use for monitoring.
`public class CustomSocketIOChannelInitializer extends SocketIOChannelInitializer {

   CustomWrongUrlHandler customWrongUrlHandler = null;

   public CustomSocketIOChannelInitializer(Configuration configuration) {
      customWrongUrlHandler = new CustomWrongUrlHandler(configuration);
   }

   protected void initChannel(Channel ch) throws Exception {
       ChannelPipeline pipeline = ch.pipeline();
       addSslHandler(pipeline);
       addSocketioHandlers(pipeline);
       // Replace wrong url handler with our custom one to allow network monitoring without logging warnings.
       pipeline.replace(SocketIOChannelInitializer.WRONG_URL_HANDLER, "CUSTOM_WRONG_URL_HANDLER", customWrongUrlHandler);
   }`

This is my custom handler:
`@Sharable
public class CustomWrongUrlHandler extends ChannelInboundHandlerAdapter {

    private final Logger log = LoggerFactory.getLogger(getClass());
    
    Configuration configuration = null;
    
    /**
    * @param configuration
    */
   public CustomWrongUrlHandler(Configuration configuration) {
       this.configuration = configuration;
    }

    @Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
       
       if (msg instanceof FullHttpRequest) {
          FullHttpRequest req = (FullHttpRequest) msg;
          Channel channel = ctx.channel();
          QueryStringDecoder queryDecoder = new QueryStringDecoder(req.getUri());

          // Don't log when port is pinged for monitoring. Must use context that starts with /ping.
          if (configuration.isAllowCustomRequests() && queryDecoder.path().startsWith("/ping")) {
              HttpResponse res = new DefaultHttpResponse(HTTP_1_1, HttpResponseStatus.BAD_REQUEST);
              channel.writeAndFlush(res).addListener(ChannelFutureListener.CLOSE);
              req.release();
              //log.info("Blocked wrong request! url: {}, ip: {}", queryDecoder.path(), channel.remoteAddress());
              return;
          } 
          
          // This is the last channel handler in the pipe so if it is not ping then log warning.
          HttpResponse res = new DefaultHttpResponse(HTTP_1_1, HttpResponseStatus.BAD_REQUEST);
          ChannelFuture f = channel.writeAndFlush(res);
          f.addListener(ChannelFutureListener.CLOSE);
          req.release();
          log.warn("Blocked wrong socket.io-context request! url: {}, params: {}, ip: {}", channel.remoteAddress() + " " + queryDecoder.path(), queryDecoder.parameters());
      }
    }`

`      CustomSocketIOChannelInitializer customSocketIOChannelInitializer = new CustomSocketIOChannelInitializer(config);
      server.setPipelineFactory(customSocketIOChannelInitializer);`

**Comment by mrniko** [comment]
OK, I have just removed it
