### ISSUE TITLE
sync with socket.io 1.4.3 - support compression

### ISSUE THREAD

**Issue by evgeny-pasynkov** [mrniko/netty-socketio#313]
Please could you add the compression support, introduced in the latest socket.io?

**Comment by mrniko** [comment]
`WebSocketServerCompressionHandler` should be used for this feature implementation. But it only available since netty-4.1.0.Beta8 version.

**Comment by mrniko** [comment]
I don't see any problems with socket.io 1.4.4 client. Could you please clarify the problem?

**Comment by evgeny-pasynkov** [comment]
I haven't tried this yet. Will be back in a few days

**Comment by mrniko** [comment]
please try it with version `master` branch

**Comment by evgeny-pasynkov** [comment]
Sorry, I haven't got how it should work. 
In your class WebSocketTransport you do create default handshakers (see method handshake(....)), which deals nothing with PerMessageDeflateServerExtensionHandshaker

**Comment by evgeny-pasynkov** [comment]
After some investigations, I suspect I have to insert the WebSocketServerCompressionHandler into the pipeline... But the exact position is not clear

**Comment by mrniko** [comment]
Don't hurry with it. There is a bug https://github.com/netty/netty/issues/4754

**Comment by evgeny-pasynkov** [comment]
Looks like I was able to get it work:
![image](https://cloud.githubusercontent.com/assets/7429642/12579127/c705d9c4-c425-11e5-9b61-220eb32932ee.png)

Just for curiosity, is it possible to get the compression statistics from the netty?

**Comment by mrniko** [comment]
It's work because you `Connection` request header has `Upgrade` value only. You are lucky :)

**Comment by mrniko** [comment]
> compression statistics 

What do you mean under `statistics`?

**Comment by evgeny-pasynkov** [comment]
I'm using socket.io 1.4.4 client....
statistics - the total compression ratio. For now I do not see if the compression actually works - "frames" tab in Chrome dev tools shows just regular socket.io text frames

**Comment by mrniko** [comment]
Confirm it works, but only with Chrome browser.

**Comment by mrniko** [comment]
> For now I do not see if the compression actually works 

I tried it with javascript socketio server same situation - Chrome doesn't show any info about data compression. But socketio server shows compression flag turned on during data sending from server to client.

**Comment by mrniko** [comment]
I can't get to work `io.netty.handler.codec.http.HttpContentCompressor` handler. Socketio client drops connection when this handler encodes the message.

**Comment by mrniko** [comment]
@evgeny-pasynkov done

**Comment by mrniko** [comment]
Have not found any compression statistics accumulation in netty code.

**Comment by mrniko** [comment]
@evgeny-pasynkov  with netty 4.1.0CR2 it works both in firefox and chrome
