### ISSUE TITLE
Weak network circumstances, the connection is not released

### ISSUE THREAD

**Issue by ChinaSimon** [mrniko/netty-socketio#314]
I used the latest version of netty-socket.io, when my webim client was on connection, I pulled out the cable, but the server did not release the connection. How could I make it released? Thank you very much!

**Comment by mrniko** [comment]
> but the server did not release the connection

All connections should be released automatically then ping timeout for each connection has reached. `pingTimeout = configuration.getPingTimeout() + configuration.getPingInterval()`

**Comment by ChinaSimon** [comment]
I had read the source code, and i know the setting. But it is useful only when the net is on connection. If you mad it dis-connected suddenly, the TCP level hasn't got it yet. 
What i use is the latest virsion of client socket.io-1.4.4. js.
You can have a try in my way: make the net disconnected or pull  out the cable when it is on connection，then you will find that it does't release the connection.
Thanks.

**Comment by mrniko** [comment]
ok, i'll try it later

**Comment by ChinaSimon** [comment]
For example, 5674 is my server port,The client is connected for a long time, It's not released.
![Uploading abcds.gif…]()

**Comment by mrniko** [comment]
@ChinaSimon Can't reproduce it. You have an ESTABLISHED state for all connections. It's strange because it's hard to have such state if client has already gone. State should be `TIME_WAIT`.

**Comment by chuangtim** [comment]
@mrniko I also have this problem.server cann`t relaese connections. I use 1.7.10 version of netty-socketio,Thank you very much!

**Comment by chuangtim** [comment]
![image](https://user-images.githubusercontent.com/8262851/57614774-9bc95b00-75ac-11e9-81cd-b6aca8c65e73.png)

**Comment by chuangtim** [comment]
@ChinaSimon are you solve this problem?

**Comment by sergiobello** [comment]
I have the same issue using socket.io.js-2.3.0 and netty-socketio-1.7.18. When the connection falls to polling it opens a lot of sockets and they keep opened (ESTABLISHED) until I close the browser.
