### ISSUE TITLE
OSGi - Address binding remains even after server.stop() issued

### ISSUE THREAD

**Issue by znikolovski** [mrniko/netty-socketio#315]
I'm using Socket.IO in an Apache Felix environment and whenever I re-deploy the bundle that manages the Socket.IO instance I get a `java.net.BindException: Address already in use` and need to restart the whole server to resolve the issue.

I followed the example as per https://github.com/mrniko/netty-socketio/issues/93.

Using Netty version 4.0.19.Final

**Comment by mrniko** [comment]
Hi!
You can turn on tcp option `reuserAddr` to resolve this via Configuration.socketConfig.reuseAddress setting.

**Comment by znikolovski** [comment]
Serves me right for not reading through all the config options :)

Worked like a treat!
