### ISSUE TITLE
Server binding issues

### ISSUE THREAD

**Issue by 12wrigja** [mrniko/netty-socketio#317]
If I try to start the server and the port I specify is in use a BindException is printed to the console. However, I can't catch this exception in order to either a.) modify the port used, or b.) wait for the port to be free and try again.

Is there a way around this issue?

**Comment by mrniko** [comment]
Hi!
You can turn on tcp option reuserAddr to resolve this problem. Use Configuration.socketConfig.reuseAddress setting.

**Comment by 12wrigja** [comment]
Thanks. I'm not sure what this does internally, but it does fix it. Are there any issues with using that setting in a production environment I should be aware of?

**Comment by mrniko** [comment]
I don't know about any production issues with it because of absence of this problem in my practice. Anyway this setting helpful for your issue and I advised it to many netty-socketio users.
