### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by evgeny-pasynkov** [mrniko/netty-socketio#319]
Running latest netty-socketio server, I get this exception sometimes:

> java.lang.IndexOutOfBoundsException: readerIndex(0) + length(10) exceeds writerIndex(4): CompositeByteBuf(ridx: 0, widx: 4, cap: 4, components=1)
>     at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1325)
>     at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1319)
>     at io.netty.buffer.AbstractByteBuf.bytesBefore(AbstractByteBuf.java:1140)
>     at com.corundumstudio.socketio.protocol.PacketDecoder.decodePackets(PacketDecoder.java:122)
>     at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:65)
>     at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:36)
>     at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
>     at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
>     at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:439)
>     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:162)
>     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
>     at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
>

**Comment by zella** [comment]
+1.  No exception in 1.7.8

**Comment by evgeny-pasynkov** [comment]
We've solved this by reverting netty back to CR1

**Comment by mrniko** [comment]
Ok, will wait for stable netty 4.1.0 version.

**Comment by mrniko** [comment]
@evgeny-pasynkov Try it with 4.1.0.CR3 please.

**Comment by evgeny-pasynkov** [comment]
CR3 works fine for me

**Comment by mrniko** [comment]
OK. Let's assume that it fixed

**Comment by theRealRizeo** [comment]
Just got the error using latest libs
