### ISSUE TITLE
How to make cluster?

### ISSUE THREAD

**Issue by dqsdhr** [mrniko/netty-socketio#330]

**Comment by wenerme** [comment]
Use Redisson or Hazelcast as StoreFactory

**Comment by aboutdata** [comment]
// Instantiate Redisson configuration
        Config redissonConfig = new Config();
        redissonConfig.useSingleServer().setAddress("127.0.0.1:6379");

        // Instantiate Redisson connection
        Redisson redisson = Redisson.create(redissonConfig);

        // Instantiate RedissonClientStoreFactory
        RedissonStoreFactory redisStoreFactory = new RedissonStoreFactory();

        // Instantiate SocketIO Configuration
        Configuration config = new Configuration();
        config.setHostname("localhost");
        config.setPort(9092);
        config.setStoreFactory(redisStoreFactory);

        // Instantiate SocketIO Server
       SocketIOServer server = new SocketIOServer(config);

**Comment by man9565** [comment]
Hello!

Import list, please tell me

**Comment by pablojr** [comment]
Added a [wiki page](https://github.com/mrniko/netty-socketio/wiki/How-To:-create-a-cluster-of-netty-socketio-servers) regarding this topic to make it more visible.

**Comment by nitinvavdiya** [comment]
I am using spring boot to create socket io server.
I created 2 instances of server(for cluster) using  radisson.
My code looks like this:

```
@SpringBootApplication
public class Application {

	
	private static final Logger LOGGER = Logger.getLogger(Application.class);
	
    @Value("${asite.socketio.hostName}")
    private String socketIOHostName;

    @Value("${asite.socketio.port}")
    private Integer socketIOport;
    
    @Value("${asite.dedisson.redissonAddress}")
    private String redissonAddress;
    
    @Autowired
    private RedissonClient redissonClient;
    
    @Bean
	public SocketIOServer socketIOServer() {
		LOGGER.info("Socket server starting on host=" + socketIOHostName + ", port=" + socketIOport);
		Configuration config = new Configuration();
		config.setHostname(socketIOHostName);
		config.setPort(socketIOport);
		
		StoreFactory redissonStoreFactory = new RedissonStoreFactory(redissonClient);
		config.setStoreFactory(redissonStoreFactory);
		SocketIOServer server = new SocketIOServer(config);
		server.start();
		LOGGER.info( "Socket server started");
		return server;
	}
	
    /**
     * 
     * @return
     */
    @Bean
    public RedissonClient getRedissonClient(){
    	LOGGER.info("creatting redisson client on redissonAddress="+redissonAddress);
    	Config config = new Config();
    	config.useSingleServer().setAddress(redissonAddress);
    	RedissonClient redisson = Redisson.create(config);
    	LOGGER.info("redisson client connected");
    	return redisson;
    }
    
    
    public Application() {
        //Nothing to be done here
    }

    public static void main(String[] args) {
        ConfigurableApplicationContext context = SpringApplication.run(Application.class, args);
    }
   
    @Bean
    public SpringAnnotationScanner springAnnotationScanner(SocketIOServer ssrv) {
        return new SpringAnnotationScanner(ssrv);
    }
}
```
Same code running in two diffrent machine(server1 and sserver2 ).
If I connect client with server1 then execute `server.getAllClients()` on server2, it returns null instead of SocketIOClient
Same thing if the client connects with server2 then I cannot get connected client on server1

The cluster is nor working for me.

**Comment by TalkIsCheapGiveMeMoney** [comment]
me too 
The cluster is not working for me.
