### ISSUE TITLE
ERROR c.c.socketio.JsonSupportWrapper 

### ISSUE THREAD

**Issue by zongchenglin** [mrniko/netty-socketio#338]
server‘s error  ：
ERROR c.c.socketio.JsonSupportWrapper - Can't read value: ["transData",{"@class":"com.shangsheng.communication.web.core.dto.SscMessage","userName":"user126","terminalCode":"37020001","afn":"10","fn":"03","pn":"0","mkTime":null,"data":null,"uuid":"2a11574e-b2d4-4e2c-89e8-78893b732261","mas":"2","seq":"0","msgType":1,"maxWaitTime":1,"timeoutInterval":60000,"maxTrytimes":2,"trytimes":1,"ptlFields":[{"key":-20,"value":"06"},{"key":-18,"value":"37020001"},{"key":-17,"value":"2"},{"key":-16,"value":"10"},{"key":-15,"value":"0"},{"key":-14,"value":"3"},{"key":-6,"value":"0"},{"key":-5,"value":"03"}]}] for type: class com.corundumstudio.socketio.protocol.Event

above is   my  socketioclient  send  message。 com.fasterxml.jackson  can not  convert  json to Object.class.

my JSON data correct 。  

com.fasterxml.jackson  is not support？

How should I solve the above problems？

changge     com.fasterxml.jackson  new－version？

**Comment by laiking** [comment]
@zongchenglin
I have the some problem too,how do u fix it?
