### ISSUE TITLE
setTransports not working

### ISSUE THREAD

**Issue by PeterL1n** [mrniko/netty-socketio#343]
`config.setTransports(Transport.WEBSOCKET);`

This code should force the server to negotiate only websockets and no polling.
However, it doesn't seam to work.
The clients can still use polling.

**Comment by pramodbms** [comment]
The same issue is seen in 1.7.5

**Comment by mrniko** [comment]
Fixed

**Comment by PeterL1n** [comment]
@mrniko Are we not ready to release 1.7.11 to maven yet?

**Comment by maksimu** [comment]
@mrniko When are you planning to release 1.7.11? Our team is waiting eagerly to get this version in maven

**Comment by mrniko** [comment]
@PeterL1n @maksimu  I hope soon!

**Comment by maksimu** [comment]
What is left or what is holding you back before you release 1.7.11?

**Comment by mrniko** [comment]
done
