### ISSUE TITLE
I want send message to this server use java, how do it ?

### ISSUE THREAD

**Issue by 362228416** [mrniko/netty-socketio#351]
？？？

**Comment by mrniko** [comment]
Have you tried a demo project?

**Comment by whg333** [comment]
for the java socketio client, you can use [socket.io-client-java](https://github.com/socketio/socket.io-client-java)

**Comment by wall-team** [comment]
@whg333 Thanks.

**Comment by 362228416** [comment]
@whg333 Thanks.
