### ISSUE TITLE
SocketIOChannelInitializer.channelRegistered is triggered multiple times for the same client connection

### ISSUE THREAD

**Issue by Kenvelo90** [mrniko/netty-socketio#359]
Hi,

I'm investigating a performance issue with our socket io service, the connection is very slow.
I noticed that the channelRegistered method at SocketIOChannelInitializer is triggered around 4-8 (inconsistent) for one client only in a sterile environments, It doesn't seem like a healthy behavior, and I'm afraid that it's affecting the performance.

**Connection Stats**

Local environment (enforcing the transports):
Websocket protocol : ~300 milliseconds
Polling protocol : ~400 milliseconds

Production environment (enforcing the transports):

Websocket protocol : ~600 milliseconds
Polling protocol : ~1500 milliseconds

Using netty-socketio 1.7.10 with the latest official js client & java client.

Thanks!

**Comment by mrniko** [comment]
have you tried to use keepAlive setting?

**Comment by Kenvelo90** [comment]
@mrniko 
The problem is on the connection (the SocketIOChannelInitializer.initChannel is called multiple times), after that everything works as expected.
Tried to use the keepAlive config, didn't help.
The issue is reproduced with the demo app + client as well.

**Comment by chxiaowu** [comment]
up

**Comment by mrniko** [comment]
`initChannel` invoked only once per channel. In your case `initChannel` invoked multiple times because at start socketio client tries to use `xhr-transport` which send few http requests before switch to `websocket` transport. If you configure your client to use `websocket` transport you won't face this issue.
