### ISSUE TITLE
why not use PooledByteBufAllocator

### ISSUE THREAD

**Issue by taojiaenx** [mrniko/netty-socketio#369]
the PooledByteBufAllocator will decreasing the comsume of CPU and memory by using jemalloc,.Though the memeory allocator is not thread-safe,it can be used in I/O thread, any Channel will in the same thread.

**Comment by bobwenx** [comment]
Hi, what you means 'PooledByteBufAllocator' is not thread-safe? can you gives some example to use 'PooledByteBufAllocator' in thread-safe way.

**Comment by mrniko** [comment]
PooledByteBufAllocator is used by default starting from netty 4.1.0. Netty-socketio already switched to it
