### ISSUE TITLE
All clients disconnect at same time

### ISSUE THREAD

**Issue by toniclecb** [mrniko/netty-socketio#375]
I implemented a server and two types of clients (javascript (browser) and java).
When I open the server and 1 javascript client and 1 java client everything works fine.
But, after I opened 10 javascript clients and 3 or 4 minutes the server show 'disconnect' for all clients, including my java client. After that, there are lots of 'connect' and 'disconnect', but no one 'event'. Sometimes after all 'disconnets' the server don't respond anymore, all client 'reconnect' and 'connect' have no answer.

Server:
```
this.server = new SocketIOServer(config);
this.server.addConnectListener(new ConnectListener() {
	@Override
	public void onConnect(SocketIOClient client) {
		System.out.println("connect" + client.getSessionId());
	}
});

server.addDisconnectListener(new DisconnectListener() {
	@Override
	public void onDisconnect(SocketIOClient client) {
		System.out.println("disconnect" + client.getSessionId());
	}
});

server.addEventListener("onLogin", String.class, new DataListener<String>() {
	@Override
	public void onData(SocketIOClient client, String key, AckRequest ackRequest) throws Exception {
		System.out.println("event");
	}
});
```
Client:
```
socket = io.connect($cookies.get('serverhost'));

socket.on('connect', function () {
	console.log('connect');
	socket.emit('onLogin', key);
});
```
Sometimes this appears:
`[error] - com.corundumstudio.socketio.transport.PollingTransport - f8133395-df1f-471f-a229-7561074fd10e is not registered. Closing connection`

**Comment by toniclecb** [comment]
I rewrote my code... and I am not facing this problem anymore, but now my only problem is: 
sometimes the client connects (client and server prints 'connect') and then the server show 'onLogin' and 'disconnect'.
The client stay waiting for a request like:
`.../socket.io/?EIO=3&transport...LOY665W&sid=d3db56dc-ba3d-4b39-9acf-f340ab7dde4f`
The client don't print 'disconnect' and wait around 100 seconds to print 'disconnect' and to try reconnect again.

**Comment by toniclecb** [comment]
In my researches I found out the error apparently is a combination of Firefox and the client lib (and polling transport).
I solved this with:
`'transports': ['websocket', 'polling']`

**Comment by mrniko** [comment]
I think this bug related to https://github.com/mrniko/netty-socketio/issues/372
