### ISSUE TITLE
How to do a simple emit?

### ISSUE THREAD

**Issue by callgino** [mrniko/netty-socketio#382]
Using version 1.7.1 .

I am running a node.js client that I want to connect to my netty-socketio server.
It is quite straightforward to connect.
I now want to start sending messages from server to client.
However, I can not seem to find any functionality that is similar to the simple socket.io emit().

I have a simple socket,on("myevent"...) in the node side, to which I am trying to emit a message from server.
I take the SocketIOClient object I received in onConnect(), and the only send API I seem to find is send(Packet).
What is this Packet? Setting its name and its data to "myevent" did not work.

**Comment by mrniko** [comment]
Hi!

You don't to use `send(Packet)` method. Use `sendEvent` method. Also take a look at https://github.com/mrniko/netty-socketio-demo for more examples
