### ISSUE TITLE
Sending to all clients except sender

### ISSUE THREAD

**Issue by Phisherman** [mrniko/netty-socketio#389]
In regular socket.io it's possible to send a message to all clients except sender like this:

```js
socket.broadcast.emit('message', "this is a test");
```

Is there a convenient method in netty-socketio?

My workaround looks like this:
```java
//in onData(SocketIOClient senderClient, Train modifiedTrain, AckRequest ackRequest)
Collection<SocketIOClient> clients = server.getAllClients();
for (SocketIOClient client : clients) {
  if(client.getSessionId().equals(senderClient.getSessionId()) == false){
    client.sendEvent(Events.modifyTrain, modifiedTrain);
  }
}
```

**Comment by JavaMachine** [comment]
@Phisherman  Is it thread safe? What if next iterating client gets disconnected?

**Comment by Phisherman** [comment]
@JavaMachine Mhm. I didn't test this case. Thanks for calling attention.

**Comment by JavaMachine** [comment]
@Phisherman My current workaround:
```
//I am adding new connection upon connection EVENT and removing upon disconnection EVENT
private ConcurrentHashMap<String, SocketIOClient> activeConnsMap = new ConcurrentHashMap<>();

for(Map.Entry<String, SocketIOClient> entry : activeSessionsMap.entrySet())
{
    if(!entry.getKey().equals(senderClient.getSessionId())){
        client.sendEvent(Events.modifyTrain, modifiedTrain);
    }
}
```

**Comment by NagRock** [comment]
Great that its on roadmap.

**Comment by mrniko** [comment]
I have added two BroadcastOperations.sendEvent methods with `excludedClient` param. Use it like this:

`server.getBroadcastOperations.sendEvent("eventName", excludedClient, eventData);`

**Comment by sanju-singh** [comment]
@mrniko 
I tried server.getBroadcastOperations.sendEvent("eventName", excludedClient, eventData);

but getting error :

ERROR com.corundumstudio.socketio.JsonSupportWrapper - Can't write value: [chat message, NamespaceClient@8d23e9cc, ChatObject@4b1dd907]

when i don't use excludedClient it is working fine but sender is also receiving the message
