### ISSUE TITLE
can't get  SocketIOClient  in AuthorizationListener

### ISSUE THREAD

**Issue by wuxingzhong** [mrniko/netty-socketio#395]
config.setAuthorizationListener( new AuthorizationListener() {
			public boolean isAuthorized(HandshakeData data) {
}
}
I want to get SocketIOClient , what should I do???

**Comment by wuxingzhong** [comment]
How to get SocketIOClient in AuthorizationListener ?

**Comment by mrniko** [comment]
SocketIOClient is not created because authorized process has not completed yet
