### ISSUE TITLE
 SocketIOClient serialization

### ISSUE THREAD

**Issue by 38202538** [mrniko/netty-socketio#396]
onData in SocketIOClient client, how to serialize and then into redis , we need to use the time and then taken out deserialization

**Comment by mrniko** [comment]
You don't need to serialize SocketIOClient object. Store its id to Redis: 
```
UUID id = SocketIOClient.getSessionId();
```
and then get it again by id:
```
SocketIOClient client = SocketIOServer.getClient(id);
```
