### ISSUE TITLE
Failed to mark a promise as success because it has succeeded already

### ISSUE THREAD

**Issue by AlexMl** [mrniko/netty-socketio#402]
> Sep 17, 2016 4:46:22 PM io.netty.channel.ChannelOutboundBuffer safeSuccess
> WARNING: Failed to mark a promise as success because it has succeeded already: DefaultChannelPromise @ 740ab58e(success)
> Sep 17, 2016 4:46:22 PM io.netty.channel.ChannelOutboundBuffer safeSuccess
> WARNING: Failed to mark a promise as success because it has succeeded already: DefaultChannelPromise @ 14cbccd8(success)
> Sep 17, 2016 4:46:22 PM io.netty.channel.ChannelOutboundBuffer safeSuccess
> WARNING: Failed to mark a promise as success because it has succeeded already: DefaultChannelPromise @ 773eab8c(success)
> Sep 17, 2016 4:46:22 PM io.netty.channel.ChannelOutboundBuffer safeSuccess
> WARNING: Failed to mark a promise as success because it has succeeded already: DefaultChannelPromise @ 235c393f(success)
> Sep 17, 2016 4:46:22 PM io.netty.channel.ChannelOutboundBuffer safeSuccess
> WARNING: Failed to mark a promise as success because it has succeeded already: DefaultChannelPromise @ 25b4e1f(success)
> Sep 17, 2016 4:46:22 PM io.netty.channel.ChannelOutboundBuffer safeSuccess
> WARNING: Failed to mark a promise as success because it has succeeded already: DefaultChannelPromise @ 25b4e1f(success)

I got a lot of those messages in my log files and I am not sure if I implemented it in a wrong way, or if there are issues in this project.

**Comment by mrniko** [comment]
Which version of Redisson and netty do you use?

**Comment by AlexMl** [comment]
I use netty-socketio 1.7.11 which comes with netty 4.1.1.Final

**Comment by nettm** [comment]
I have same question when i make pressure test.
netty-socketio 1.7.12

**Comment by cicimon** [comment]
I have the same question when about 100 clients connect.
netty-socketio 1.7.12
netty 4.1.9

**Comment by mrniko** [comment]
Fixed

**Comment by robymus** [comment]
Could you please reopen the issue? (or should I create a new one?) While the fix above fixed one of the issues causing this error and reduced the occurrence rate drastically, under high load a different cause results in the same error. Unfortunately I have noticed this only after sending my pull request (i have tested it only under medium load).

I'm working on a more generic fix to cover this issue. Sorry for the hasty pull request.

**Comment by robymus** [comment]
Problem analysis:

The handleWebsocket method of EncoderHandler creates multiple write operations on the channel from a single write operation, and some of them gets the result promise passed. These write operations will ultimately (upon completion on the network layer) set the promise to success, but the handleWebsocket method explicitly sets it to success too. Under specific timing situations (high load), this explicit setting to success happens before the network layer sets it to success.

Possible solutions:
1) assemble all the encoded results into a byte buffer and call write on all of them at once, with the promise passed
2) pass the promise as the parameter of the last write operation in the block
3) retain the channel futures from all writes and set up an async handler that will set the promise to success/failure based on the channel future results, when these are available

I would not go with 2), as it feels like unstable magic.

1) is very easy to implement and the only possible backside is that the method has to be slightly restructured.

3) would keep the method structure intact with some additional code present, but this additional code would be very complicated.

I prefer to go with 1), i will run some tests with it and send a pull request after a few days, running our system through a few high traffic periods.

**Comment by mrniko** [comment]
Thanks for a solution! Looks good. Could you make a PR?

**Comment by robymus** [comment]
I will deploy it to our environment later today and run some tests under load, I want to avoid a premature pull request now. I will make the PR on Monday, if real life load tests succeed.

**Comment by mrniko** [comment]
@robymus any update?

**Comment by robymus** [comment]
Sorry, totally forget about it. Thanks for the reminder. We have deployed it in production and it works fine, I will create a pull request right now.

**Comment by mrniko** [comment]
Any update?
