### ISSUE TITLE
how to expose a http api

### ISSUE THREAD

**Issue by jjavaboy** [mrniko/netty-socketio#403]
I want to send a http request to the netty-socketio server.

**Comment by mrniko** [comment]
Create your own handler which extends `ChannelInboundHandlerAdapter` and add it to netty pipeline

**Comment by jjavaboy** [comment]
Thank you.

**Comment by bruno-ortizgb** [comment]
I need some help with that!

I want to receive a simple HttpRequest and send back a simple HttpResponse.

Can anyone help me with that?

**Comment by pablojr** [comment]
@bruno-ortizgb as mentioned before you need to work with the Netty server pipeline by adding your our handler. Please take a look at the several examples regarding how to use Netty in this respect, i.e. http://www.programcreek.com/java-api-examples/index.php?api=io.netty.channel.ChannelInboundHandlerAdapter
The issue you're trying to solve is not netty-socketio related.

**Comment by shivamSharmaMWP** [comment]
@pablojr , please create a sample java class, that support this. not able to find a proper solution. @jjavaboy  do you have working example.

**Comment by pablojr** [comment]
> not able to find a proper solution

What have you attempted so far?
Have you checked the link I posted previously? There are several examples there...

**Comment by shivamSharmaMWP** [comment]
@pablojr 
i enabled the field setAllowCustomRequests(true) in config, created on http handler by extending ChannelInboundHandlerAdapter class, and inserted into the netty pipeline using .addLast() method.
but that handler is not able to pick the http request. and was throwing " Blocked wrong socket.io" .

i need to debug line by line for where to put the httpHandler and inserted handler before WrongUrlHandler class, then i was able to receive request there. 

if there is a better approach then what i have tried, please let me know.

as a framework, if you are providing setAllowCustomRequests() method for allowing for customized http requests, then the framework should also expect the httpHandler too and your implementation should automatically inject user's provided handler at appropriate place.

com.corundumstudio.socketio.handler.AuthorizeHandler.java file is checking on allowCustomRequests but didn't provide placeholder if any handler is provided by user or not.
