### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by pengfei-xu** [mrniko/netty-socketio#408]
public void onDisconnect(SocketIOClient client) {
        Set<String> joinedRooms = client.getAllRooms();  
        allClients.remove(client.getSessionId());
        leave(getName(), client.getSessionId());
        storeFactory.pubSubStore().publish(PubSubType.LEAVE, new JoinLeaveMessage(client.getSessionId(), getName(), getName()));

```
    for (String joinedRoom : joinedRooms) {
        leave(roomClients, joinedRoom, client.getSessionId());
    }
    clientRooms.remove(client.getSessionId());
```

this code do not  storeFactory.pubSubStore().publish to another server , this will cause memory leak .  clientRooms and  roomClients will  increase forerver

**Comment by mrniko** [comment]
which netty-socketio version do you use?

**Comment by pengfei-xu** [comment]
I used master code

**Comment by mrniko** [comment]
@CrazyIvan007 Hi! Do you have same issue?

**Comment by CrazyIvan007** [comment]
I never used the pubSubStore, so this could be possible.

**Comment by mrniko** [comment]
@pengfei-xu Can you suggest a patch?

**Comment by pengfei-xu** [comment]
for (String joinedRoom : joinedRooms) {
            leaveRoom(joinedRoom, client.getSessionId());
     }
    when onDisconnect pubSubStore to another server to clientRooms  remove

**Comment by mrniko** [comment]
@pengfei-xu I see you founded a cause. Can I close this issue now?

**Comment by pengfei-xu** [comment]
ok,thks
