### ISSUE TITLE
SocketIO cluster

### ISSUE THREAD

**Issue by amit2103** [mrniko/netty-socketio#411]
Hi,

Is there anyway to create a cluster of netty-socketio servers. So that we have failover etc.

Regards

**Comment by JavaMachine** [comment]
#330

**Comment by pablojr** [comment]
Added a [wiki page](https://github.com/mrniko/netty-socketio/wiki/How-To:-create-a-cluster-of-netty-socketio-servers) regarding this topic to make it more visible.

**Comment by mrniko** [comment]
@pablojr Thanks a lot!

**Comment by devpage** [comment]
@JavaMachine good
