### ISSUE TITLE
 Establishing a tunnel via proxy server failed.

### ISSUE THREAD

**Issue by pengfei-xu** [mrniko/netty-socketio#418]
![image](https://cloud.githubusercontent.com/assets/15759076/20101462/0db88240-a5fd-11e6-8f06-ae45396367e4.png)

WebSocket connection to 'ws://websocket.2dfire.com/socket.io/?xtoken=70D2C0552F734D80E666014AE5BACEF25E0817906F1926A46BCE3442141FCD9D&entityId=00033380&seatCode=10&EIO=3&transport=websocket' failed: Establishing a tunnel via proxy server failed.

**Comment by pablojr** [comment]
It looks like you're using a client trying to connect to a server at websocket.2dfire.com for a websocket session, but the client cannot handle going through a proxy server, am I right? If so, the issue isn't related to netty-socketio...

Could you please describe what you're attempting to do? and describe you're environment as well please.

**Comment by pengfei-xu** [comment]
yes。I want trying to connect to a server at websocket.2dfire.com . I used Alibaba Cloud  SLB proxy server

**Comment by pablojr** [comment]
You didn't describe your environment very well. Please help the rest help you!
What client are you using in such connection?
Is the server at websocket.2dfire.com a netty-socketio one?

**Comment by pengfei-xu** [comment]
I have two server of websocket.2dfire.com, have one Alibaba Cloud SLB proxy server. client is Html5 of socket.io to connection.connection always appear the client cannot handle going through a proxy server,

**Comment by pablojr** [comment]
With due respect, I cannot see where netty-socketio server is within your environment.
It seems that your problem is a malcongfigured **socketio client** not able to connect to a proxy server. You may want to post this question to your client's forum.

**Comment by pengfei-xu** [comment]
ths! I sloved it。  Alibaba Cloud SLB proxy server appear problem,I restart it fix it.
