### ISSUE TITLE
please write how to generate / sign the JKS key for the SSL demo

### ISSUE THREAD

**Issue by OrlovProxor** [mrniko/netty-socketio#477]
https://github.com/mrniko/netty-socketio-demo/blob/master/server/src/main/java/com/corundumstudio/socketio/demo/SslChatLauncher.java

I can not find a working example for creating a certificate
very much necessary, thank you

**Comment by pablojr** [comment]
Do you mean creating your server certificate? What about this [tutorial](https://jamielinux.com/docs/openssl-certificate-authority/)? It covers creating the root CA (self-signed obviously) along with server and client certificates using OpenSSL commands.

**Comment by pablojr** [comment]
I realized that you may be referring to how getting the server certificate into the Java keystore (.jks) so something like [this](https://www.grim.se/guide/jre-cert) also may help.

**Comment by OrlovProxor** [comment]
how i solved my problem, i set up tomcat and made self signed jks key for it, check the key on tomcat, then just took the key
