### ISSUE TITLE
Unknown channel option 'SO_LINGER' for channel '[id: 0xaedd4e7b]'

### ISSUE THREAD

**Issue by AlexMl** [mrniko/netty-socketio#481]
Since I updated to 1.7.13 with netty 4.1.15.Final I get this warning on start up:

`[io.netty.bootstrap.ServerBootstrap] [WARN] Unknown channel option 'SO_LINGER' for channel '[id: 0xaedd4e7b]'`
The id is different every time, but that shouldn't be a surprise.

It does not seem to have an effect of our production environment, but it is still a warning.

**Comment by Maxinim** [comment]
Hi there,
Have this warning too. What does that mean and how to prevent this ?
I'm like AlexMI, I don't like warnings :)
