### ISSUE TITLE
Big memory problems

### ISSUE THREAD

**Issue by AlexMl** [mrniko/netty-socketio#489]
Not long ago, I switched from sending JSONObjects to sending binary data. That worked pretty good since I no longer had encoding errors.
We changed parts of our backend to the new system and now we are having a lot of problems with OutOfMemory Errors. I also get the Leak detection message from netty.

We don't have many clients, but we send a lot of data.

I'm using the latest netty-socketio snapshot from master, even tried updating to latest netty (4.1.16.Final), but no difference.

I hope the stacktraces help. I attached them below, since they are pretty ugly.

[leakDetection.log](https://github.com/mrniko/netty-socketio/files/1425483/leakDetection.log)
[oom-exception.log](https://github.com/mrniko/netty-socketio/files/1425484/oom-exception.log)

Let me know if you need anything more to solve this.

Thank you.
Alex

**Comment by mrniko** [comment]
Fixed in https://github.com/mrniko/netty-socketio/commit/1ab1abffefa096433bb216ec3ad77f00bbb025f7
