### ISSUE TITLE
java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by fabiodipaolo** [mrniko/netty-socketio#490]
I have this error when my server stops annd starts. Probably sockets are in TIME_WAIT. How can  I solve it? Thanks in advance

**Comment by AlexMl** [comment]
You need to set the reuseAddress option:
```
 Configuration configuration = new Configuration();
 SocketConfig socketConfig = configuration.getSocketConfig();
 socketConfig.setReuseAddress(true);

```

**Comment by fabiodipaolo** [comment]
It works, thanks!!!

**Comment by pablojr** [comment]
I added a wiki page to document (how-to) this issue and the solution
