### ISSUE TITLE
[emergency]send data question on cluster Solution at wiki's suggestion

### ISSUE THREAD

**Issue by liuliliGithub** [mrniko/netty-socketio#494]
hi, i use netty-socketio:1.7.12, when i build cluster netty-socket-io servers(example: server A and Server B).then i found that the connect channel by redis pub only pub client session id(client1 connect serverA then serverA pub message by redis to  server B, then in server B has client1's sessionId).but if i want that send data by server B to client1 is impossible. beacause server B only have sessionId not client, then i dont understand how the cluster solution solve i said Scenes. please my paste code:
```java
// BaseStoreFactory.java
// sub connect msg,so namespace allClients have not sessionId mapps client
 pubSubStore().subscribe(PubSubType.CONNECT, new PubSubListener<ConnectMessage>() {
            @Override
            public void onMessage(ConnectMessage msg) {
                authorizeHandler.connect(msg.getSessionId());
                log.debug("{} sessionId: {}", PubSubType.CONNECT, msg.getSessionId());
            }
        }, ConnectMessage.class);
```
```java
// Namespace.java
// send msg to browser client
    public Iterable<SocketIOClient> getRoomClients(String room) {
        Set<UUID> sessionIds = roomClients.get(room);
        if (sessionIds == null) {
            return Collections.emptyList();
        }
        List<SocketIOClient> result = new ArrayList<SocketIOClient>();
        for (UUID sessionId : sessionIds) {
            SocketIOClient client = allClients.get(sessionId);
            if(client != null) {
                result.add(client);
            }
        }
        return result;
    }
```

**Comment by yogeshkaushik** [comment]
Is there any solution to this problem????? Where we want **SERVER-B** to respond to those clients, which initially made connection with **SERVER-A** and redis passed the session-id information to **SERVER-B**

**Comment by wuxudong** [comment]
The question is same as #504 .
In a word, Impossible .

**Comment by yogeshkaushik** [comment]
@liuliliGithub 

> then i dont understand how the cluster solution solve i said Scenes

According to my understanding - the cluster solution provided in netty-socketio is for broadcasting messages across multiple servers not for the scenario you have mentioned. Have a look at class `BroadcastOperations`.

Here is stackoverflow [link](https://stackoverflow.com/questions/46538493/make-cluster-of-netty-socketio-server/47766903#47766903)  for the same doubt.

**Comment by liuliliGithub** [comment]
ok, i will try broadcastOperation.then i reply comment.
