### ISSUE TITLE
How To: create a cluster of netty socketio servers

### ISSUE THREAD

**Issue by gohitbear** [mrniko/netty-socketio#498]
I use redisson version is 3.5.5

**but there is no method ：**
Config redissonConfig = new Config();
Redisson redisson = Redisson.create(redissonConfig);

**the current method is : **
RedissonClient redissonClient = Redisson.create(redissonConfig);

so how can I use the RedissonStoreFactory in my socket server ? 

thanks

**Comment by pablojr** [comment]
@gohitbear I updated wiki page to be consistent with method RedissonStoreFactory(RedissonClient redisson) as you are supposed to use RedissonClient redissonClient = Redisson.create(redissonConfig);
Please try and let us know.

**Comment by gohitbear** [comment]
success ! thx
