### ISSUE TITLE
Connecting to clients in Cluster Using redis

### ISSUE THREAD

**Issue by yogeshkaushik** [mrniko/netty-socketio#504]
Hi @mrniko , I have two netty-socketio servers (lets say **A** and **B**) running on different machines, and am using Redis for pub/sub. My question is that, when a client (lets say Alpha) connects to server **A** it publishes PubSubMessage with session-id and the other server **B** gets only session-id  NOT the ClientHead, in that case server **B** can't connect to the client Alpha, **getClient()** method on server **B** will return null, So what solution do you propose in this scenario where we want all servers present in cluster to keep connection to each client.
Any hint will be appreciable.

**Comment by wuxudong** [comment]
I don’t think you can make it. The connection is initiated by the client, and it connects to server a, then only server a can send packets to it. If other services want to send messages to client, you can use server a as a proxy/delegate.

**Comment by yogeshkaushik** [comment]
How naive of me, didn't think about the basics of a tcp connection. It is not possible from netty server to initiate connection to client even if it has all the channel information.

Closing the issue.
