### ISSUE TITLE
Send UTF-8 message "你好" but recieve "??",  if polling is used

### ISSUE THREAD

**Issue by HenryOrz** [mrniko/netty-socketio#515]
Hi,
When I send message contains utf-8 characters like "你好", I recieve "??"
For example, the message is:
`161:42["CUSTOMER_MESSAGE_SEND",{"message":"你好"}]`
but I recieve
`161:42["CUSTOMER_MESSAGE_SEND",{"message":"??"}]`

I captured the requeset and got:
`161%3A42%5B%22CUSTOMER_MESSAGE_SEND%22%2C%7B%22message%22%3A%22%E4%BD%A0%E5%A5%BD%22%7D%5D`
it's the message after utf8  url encode, I'm sure that server recieved the right message

when I debug the com.corundumstudio.socketio.handler.InPacketHandler,channelRead0()
```java
    @Override
    protected void channelRead0(io.netty.channel.ChannelHandlerContext ctx, PacketsMessage message)
                throws Exception {
        ByteBuf content = message.getContent();
        ClientHead client = message.getClient();
        if (log.isTraceEnabled()) {
            log.trace("In message: {} sessionId: {}", content.toString(CharsetUtil.UTF_8), client.getSessionId());
        }
```

I print **_content_** in utf8 , but I got `["CUSTOMER_MESSAGE_SEND",{"message":"??"}]`, how can I fix this problem?

My environment and config:
browser: ie9
netty-socketio.version: 1.7.12
server: tomcat8

socketio config

```xml
    <bean name = "socketIOConfiguration" class="com.corundumstudio.socketio.Configuration">
        <property name="port" value="9099"/>
        <property name="socketConfig" ref="socketConfig"/>
    </bean>

    <bean name = "socketConfig" class="com.corundumstudio.socketio.SocketConfig">
        <property name="reuseAddress" value="true"/>
    </bean>

    <bean name="socketIOServer" class="com.corundumstudio.socketio.SocketIOServer">
        <constructor-arg  ref="socketIOConfiguration"/>
    </bean>

    <bean class="com.corundumstudio.socketio.annotation.SpringAnnotationScanner">
        <constructor-arg  ref="socketIOServer"/>
    </bean>
```

HTTP params:
```
   b64: 1
   EIO: 3
   j: 6
   t: M5gmmv5
   transport: polling
```

**Comment by pablojr** [comment]
Hi, is it possible for you to debug and check what is the actual value of "content" just after this sentence:
`ByteBuf content = message.getContent();`
you should see bytes xE4xBDxA0xE5xA5xBD just before the end, just before the last three bytes for "}]
If you see that the server actually received the proper bytes for your message 你好
If not, the server didn't receive the right value, or something got messed up in netty-socketio before reaching this method you're referring.

**Comment by HenryOrz** [comment]
Thanks,
I checked value of "content" of this sentence:
`ByteBuf content = message.getContent();`
and I got `x3Fx3Fx22x7Dx5D` at last bytes, it's `??"}]`

But I'm pretty sure that I recieve the right value, according to com.corundumstudio.socketio.SocketIOChannelInitializer, I found that the first decoder in ChannelPipeline is HttpRequestDecoder
```java
    protected void addSocketioHandlers(ChannelPipeline pipeline) {
        pipeline.addLast(HTTP_REQUEST_DECODER, new HttpRequestDecoder());
        pipeline.addLast(HTTP_AGGREGATOR, new HttpObjectAggregator(configuration.getMaxHttpContentLength()) {
            @Override
            protected Object newContinueResponse(HttpMessage start, int maxContentLength,
                    ChannelPipeline pipeline) {
                return null;
            }

        });
        pipeline.addLast(HTTP_ENCODER, new HttpResponseEncoder());

        if (configuration.isHttpCompression()) {
            pipeline.addLast(HTTP_COMPRESSION, new HttpContentCompressor());
        }

        pipeline.addLast(PACKET_HANDLER, packetHandler);
```
I put a breakpoint on `decode()` method of HttpRequestDecoder (actually the method is inherit from HttpObjectDecoder), and I got `%E4%BD%A0%E5%A5%BD%22%7D%5D`  at last bytes of params, it's the right message of `你好"}]`
But when ChannelPipeline pass this message to packetHandler, it goes wrong, I got `x3Fx3Fx22x7Dx5D` at last bytes, it's `??"}]`
It seems that there is something wrong in decoders

**Comment by HenryOrz** [comment]
Hi,
I think I have found the problem at com.corundumstudio.socketio.protocol.PacketDecoder
```java
// TODO optimize
public ByteBuf preprocessJson(Integer jsonIndex, ByteBuf content) throws IOException {
    String packet = URLDecoder.decode(content.toString(CharsetUtil.UTF_8), CharsetUtil.UTF_8.name());

    if (jsonIndex != null) {
        /**
        * double escaping is required for escaped new lines because unescaping of new lines can be done safely on server-side
        * (c) socket.io.js
        *
        * @see https://github.com/Automattic/socket.io-client/blob/1.3.3/socket.io.js#L2682
        */
        packet = packet.replace("\\\\n", "\\n");

        // skip "d="
        packet = packet.substring(2);
    }
    packet = new String(packet.getBytes(CharsetUtil.ISO_8859_1), CharsetUtil.UTF_8);

    return Unpooled.wrappedBuffer(packet.getBytes(CharsetUtil.UTF_8));
}
```

I have got the right message from the first line of this method
`String packet = URLDecoder.decode(content.toString(CharsetUtil.UTF_8), CharsetUtil.UTF_8.name());`

But this sentences below convert the utf8 message to `??`
`packet = new String(packet.getBytes(CharsetUtil.ISO_8859_1), CharsetUtil.UTF_8);`
What's the purpose of this confusing sentences?

**Comment by pablojr** [comment]
An additional issue is that even when the second assignment for packet is fixed (changing from ISO_8859_1 to UTF_8) then packet is again assigned a new value as an Unpooled.wrappedBuffer. I don't see the purpose of that last action.

**Comment by HenryOrz** [comment]
I create a [pull request](https://github.com/mrniko/netty-socketio/pull/516)

**Comment by pablojr** [comment]
Please don't commit (or provide a patch) with commented code. If code isn't relevant, just remove it and the commit message will let the world know about the reasons why such snippet was removed

**Comment by HenryOrz** [comment]
sorry, i will remove it

**Comment by HenryOrz** [comment]
[https://github.com/mrniko/netty-socketio/pull/516](https://github.com/mrniko/netty-socketio/pull/516)
