### ISSUE TITLE
Secure and non-secure connections at the same time?

### ISSUE THREAD

**Issue by pablojr** [mrniko/netty-socketio#518]
Could it be possible to configure netty-socketio server to listen to both secure (i.e. wss) or non-secure (i.e. ws) connections at the same time?
I know that I can pass the location of a JKS keystore and that way the server will provide secure connections, but I'm not sure if doing so it still would allow non-secure connections.
Thank you in advance.

**Comment by mrniko** [comment]
I would add ability to netty-socketio to use shared eventGroup between two clients connected to wss and ws.

**Comment by mrniko** [comment]
All you need to do is to supply shared eventGroup to both clients here

https://github.com/mrniko/netty-socketio/blob/master/src/main/java/com/corundumstudio/socketio/SocketIOServer.java#L176

**Comment by pablojr** [comment]
I'm not sure I'm following regarding the proposed change, or very likely I didn't explain well my use case. I have a netty-socketio server listening to non-secure connections on port X. 
Now if I configure the server providing a keystore and password, I'd like it to accept a client with a secure connection to port X and another client with a non-secure connection to port X. Clients won't talk to each other, they will receive same updated data from server to display in GUIs

**Comment by mrniko** [comment]
Sorry, my mistake. You should register a new netty handler which able to detect both secure and non-secure modes. Then it removes or adds corresponding handler to channel pipeline.

**Comment by pablojr** [comment]
@mrniko thank you for your guidance. I finally created a PortUnificationHandler class, mainly inspired by the [port unification example](http://netty.io/3.6/xref/org/jboss/netty/example/portunification/PortUnificationServerHandler.html) in Netty and added such handler between the FlashPolicyHandler and the SSLHandler in SocketIOPipelineFactory class.
The PortUnificationHandler.decode() method will detect an encrypted message, so it will remove the non-secure websocket handler, or if not encrypted message will remove the secure websocket handler and the ssl handler. Finally in either case, it'll remove itself and the message will continue its decoding flow as it is now.

**Comment by jianhaozh** [comment]
> @mrniko thank you for your guidance. I finally created a PortUnificationHandler class, mainly inspired by the [port unification example](http://netty.io/3.6/xref/org/jboss/netty/example/portunification/PortUnificationServerHandler.html) in Netty and added such handler between the FlashPolicyHandler and the SSLHandler in SocketIOPipelineFactory class.
> The PortUnificationHandler.decode() method will detect an encrypted message, so it will remove the non-secure websocket handler, or if not encrypted message will remove the secure websocket handler and the ssl handler. Finally in either case, it'll remove itself and the message will continue its decoding flow as it is now.

Can you show me how you are implement this ,i  also have this issue, any detail informantion will be apperacited!
