### ISSUE TITLE
⚠Custom jackson mapper configuration per event

### ISSUE THREAD

**Issue by n0ise9914** [mrniko/netty-socketio#571]
Is there any way to send serialized object as string (avoiding duplicate serialization),
I saw there's a config.setJsonSupport(...), but i need different Jackson configuration per each outgoing event.

using version 1.7.15

**Comment by DroidUnknown** [comment]
What i saw in the demo code is
```
       server.addEventListener("chatevent", ChatObject.class, new DataListener<ChatObject>() {
            @Override
            public void onData(SocketIOClient client, ChatObject data, AckRequest ackRequest) {
                server.getBroadcastOperations().sendEvent("chatevent", data);
            }
        });
```
Which is actually sent as json object.

**Comment by n0ise9914** [comment]
Thank you, but it uses a default jackson parser mapper configuration,

I need to pass serialized object as string to sendEvent or custom mapper config per message.
