### ISSUE TITLE
Java socket.io client compatibility 

### ISSUE THREAD

**Issue by pestyb** [mrniko/netty-socketio#573]
Hey,

Currently in our project we use the version of netty-socketio version 1.7.15 , and we are upgrading the version of our client, but not really sure about which version to pick. 

The decision is between version 1.0.0 https://github.com/socketio/socket.io-client-java and 0.9.0. 

As the github page states: "The current version of socket.io-client-java doesn't support socket.io server 1.x. Please use socket.io-client-java 0.9.x for that instead." 

On the other hand, Netty states that it supports 1.0+ version of socket.io client, is that true? 

Thanks!

**Comment by n0ise9914** [comment]
netty-socketio 1.7.15 is compatible with socket.io-client 2.0.0

**Comment by pestyb** [comment]
Thanks @n0ise9914, it seems to be working fine!

**Comment by pablojr** [comment]
@pestyb is your issue solved? if so, please close this post. Thanks
