### ISSUE TITLE
How many concurrent connections can this library handle?

### ISSUE THREAD

**Issue by DroidUnknown** [mrniko/netty-socketio#575]
Since I am going to use it in my production environment, I am a little concerned about scalability. What if I get lots of users logged in concurrently.

**Question**: Is there a limit to how many connections it can handle?

**Comment by pablojr** [comment]
> Question: Is there a limit to how many connections it can handle?
Answer: Yes. As always in life.

**Comment by pablojr** [comment]
@DroidUnknown just seriously, I guess that even when you find some figures regarding netty-socketio capacity (see Performance [here](https://github.com/mrniko/netty-socketio), values from 2014!), it's up to you to really go and test it under your specific environment/constraints to have an actual valid number for your application/solution. Regards.

**Comment by Maypeur** [comment]
I haven't any number for you but, i would say that there are severals limits based on your implementation, your hardware and your OS more than the library itself :
- Memory available
- Bandwith available
- Max concurrents file that can be opened by your OS
- The CPU used by your worker...
- Max thread depending on your OS
- ...

For me, i use one thread for each client (managed in a thread pool), and i never have performance problem (i reached 2000 simultaneous connections).

**Comment by DroidUnknown** [comment]
thanks
