### ISSUE TITLE
Issues with tab cloning

### ISSUE THREAD

**Issue by zepinos** [mrniko/netty-socketio#593]
Hi.

I am using netty-socketio to implement a 1: 1 chat with my browser. The first time I connect to the server using the UI, I get a sessionId, which is stored in my browser as a cookie. However, if I open the same window by using "duplicated tap" in the browser, the sessionId will not be issued like netty's channelId, so the message will be sent only to the new window. And AckRequest only sends messages to the first opened tab.

What I want to do is to notify the existing window when a new window is opened, letting it know that a new window has been opened, so that the window can be closed and both the AckRequest and the event are transferred to the new window. Conversely, even if a new window is opened, it is possible to continue the conversation in the existing window and close the new window. In other words, one user can only conduct a conversation in one window.

I ask you to provide me with an idea that can be solved.

Thanks.

**Comment by StereoApp** [comment]
I have the same problem, The netty-socketio always restore a connect from the Cookies named 'io'.
cause by [https://github.com/mrniko/netty-socketio/commit/9ccdb36019e1ca981308c4456963c9ef75d82f56](url)

**Comment by Ben-Mark** [comment]
is there any fix for this issue on current master?

**Comment by DestinyInHand** [comment]
I found the version 1.7.7 can solve the problem.

**Comment by Yuanxiangz** [comment]
@mrniko  what about we add a config to serve different requirements? please see my pull request #630 

![asds](https://user-images.githubusercontent.com/11549125/50210117-4d72b000-03b0-11e9-996b-dedc349bb379.png)

**Comment by zhoulinyun** [comment]
All these open windows use the same session Id . Can AckRequest send messages to all open windows
