### ISSUE TITLE
Not working remote behind nginx

### ISSUE THREAD

**Issue by ujja** [mrniko/netty-socketio#609]
Hello boys,

Socket works well locally. But remote, after deploy it is not working.

1. It is behind NGinx. Is this config correct?
location /socket.io {
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_http_version 1.1;
#proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header Host $host;
proxy_pass http://localhost:9092;
}

2. What is the correct hostname for server in this case? Is it required at all?

**Comment by ujja** [comment]
Answer is here:
https://github.com/mrniko/netty-socketio/wiki/Using-netty-socketio-server-in-AWS

**Comment by pablojr** [comment]
@ujja so you confirm that the instructions in the wiki worked for you? Thanks.

**Comment by ujja** [comment]
Yes, I confirm. Thanks!
