### ISSUE TITLE
usage of netty-socketio in Android

### ISSUE THREAD

**Issue by jcdufourd** [mrniko/netty-socketio#62]
In ResourceHandler.setContentTypeHeader, the use of MimetypesFileTypeMap 
makes netty-socketio unusable on Android.
I do not know yet how to fix that.

**Comment by HuskarHuang** [comment]
Hello, my android device as socketio server can receive client connect,but soon it will disconnect
10:05:50.459 12833-12956 XLog         com.gmd.cardrecord  I  #onDisconnect getRemoteAddress = /10.166.1.252:13496,52cd37ae-d5ff-4208-af5a-13889a102193
10:05:52.506 12833-12979 XLog         com.gmd.cardrecord  I  #onConnect getRemoteAddress = /10.166.1.252:13543,d4dbb467-f574-4a61-af69-e4a51e7f6aa1
10:05:55.559 12833-12956 XLog         com.gmd.cardrecord  I  #onDisconnect getRemoteAddress = /10.166.1.252:13497,6df25b51-8036-4b4b-a150-f15eb4fc04cf
10:05:57.583 12833-12980 XLog         com.gmd.cardrecord  I  #onConnect getRemoteAddress = /10.166.1.252:13548,fce18c34-c1c5-4055-8bea-0e0989b79808
10:06:00.659 12833-12956 XLog         com.gmd.cardrecord  I  #onDisconnect getRemoteAddress = /10.166.1.252:13499,8051ae33-98c4-4526-b2ec-4a20775c7661
10:06:02.723 12833-12981 XLog         com.gmd.cardrecord  I  #onConnect getRemoteAddress = /10.166.1.252:13550,a1ba98f3-47cc-448d-a378-02fe612d8a88
10:06:05.760 12833-12956 XLog         com.gmd.cardrecord  I  #onDisconnect getRemoteAddress = /10.166.1.252:13502,f4fa20e5-91d5-4b69-8492-03718b1a90a8
10:06:07.841 12833-12982 XLog         com.gmd.cardrecord  I  #onConnect getRemoteAddress = /10.166.1.252:13552,0a183738-b813-484f-b0f2-47e34d5a4ab1
10:06:10.859 12833-12956 XLog         com.gmd.cardrecord  I  #onDisconnect getRemoteAddress = /10.166.1.252:13503,53d80b14-a19e-4409-9485-f29a5e4fd150
10:06:12.974 12833-12984 XLog         com.gmd.cardrecord  I  #onConnect getRemoteAddress = /10.166.1.252:13557,00247baa-f602-4161-9890-fe0ea4fc6379
10:06:15.959 12833-12956 XLog         com.gmd.cardrecord  I  #onDisconnect getRemoteAddress = /10.166.1.252:13508,e7e34eac-b62d-498a-8b1a-a62d6d0c9328
10:06:18.193 12833-12993 XLog         com.gmd.cardrecord  I  #onConnect getRemoteAddress = /10.166.1.252:13558,fdbbdd25-1383-4fca-b5df-c555503aed0e
10:06:21.059 12833-12956 XLog         com.gmd.cardrecord  I  #onDisconnect getRemoteAddress = /10.166.1.252:13509,d71209b2-2a31-4ff7-b379-c57d58efe081
10:06:23.306 12833-12996 XLog         com.gmd.cardrecord  I  #onConnect getRemoteAddress = /10.166.1.252:13563,b2cc0813-2f69-4f98-a1cb-5943bcb1896b
10:06:26.259 12833-12956 XLog         com.gmd.cardrecord  I  #onDisconnect getRemoteAddress = /10.166.1.252:13510,252ff331-2fb5-4da6-984d-d0b09787c7c1
10:06:28.446 12833-12997 XLog         com.gmd.cardrecord  I  #onConnect getRemoteAddress = /10.166.1.252:13564,4e0fc298-5123-406e-8a8a-fe34b3a7788b
10:06:31.359 12833-12956 XLog         com.gmd.cardrecord  I  #onDisconnect getRemoteAddress = /10.166.1.252:13518,7aadbfb8-211f-4bc1-8322-903a18fc9c86
