### ISSUE TITLE
Memory problems  version 1.7.17

### ISSUE THREAD

**Issue by arestory** [mrniko/netty-socketio#676]
After the number of connections dropped, the memory remained too high to drop

**Comment by DancingCorp** [comment]
We found the same problem

**Comment by cjpw** [comment]
Configuration.setRandomSession(true);



chenju_1990@sina.cn
 
From: DancingCorp
Date: 2019-11-07 18:18
To: mrniko/netty-socketio
CC: Subscribed
Subject: Re: [mrniko/netty-socketio] Memory problems version 1.7.17 (#676)
We found the same problem

**Comment by daiwen305** [comment]
> Configuration.setRandomSession(true); chenju_1990@sina.cn From: DancingCorp Date: 2019-11-07 18:18 To: mrniko/netty-socketio CC: Subscribed Subject: Re: [mrniko/netty-socketio] Memory problems version 1.7.17 (#676) We found the same problem — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

It doesn't work.

`
       Configuration config = new Configuration();
        config.setPort(nettyConfig.getPort());
        config.setMaxFramePayloadLength(1024 * 1024);
        config.setMaxHttpContentLength(1024 * 1024);
        config.setTransports(Transport.WEBSOCKET);
        config.setOrigin(null);
        config.setPreferDirectBuffer(false);
        config.setRandomSession(true);
        config.setBossThreads(8);
        config.setWorkerThreads(400);
`
rss reach to 1.32G when startup, and up to 2.1G after all clients disconnection.

**Comment by cjpw** [comment]
I'm sorry. My answer is another question #657 

> > Configuration.setRandomSession(true); [chenju_1990@sina.cn](mailto:chenju_1990@sina.cn) From: DancingCorp Date: 2019-11-07 18:18 To: mrniko/netty-socketio CC: Subscribed Subject: Re: [mrniko/netty-socketio] Memory problems version 1.7.17 (#676) We found the same problem — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> It doesn't work.
> 
> ```
>     Configuration config = new Configuration();
>     config.setPort(nettyConfig.getPort());
>     config.setMaxFramePayloadLength(1024 * 1024);
>     config.setMaxHttpContentLength(1024 * 1024);
>     config.setTransports(Transport.WEBSOCKET);
>     config.setOrigin(null);
>     config.setPreferDirectBuffer(false);
>     config.setRandomSession(true);
>     config.setBossThreads(8);
>     config.setWorkerThreads(400);
> ```
> 
> rss reach to 1.32G when startup, and up to 2.1G after all clients disconnection.

**Comment by mrniko** [comment]
Fixed in https://github.com/mrniko/netty-socketio/issues/868
