### ISSUE TITLE
the v1.7.17 version got an logic error

### ISSUE THREAD

**Issue by yuzun** [mrniko/netty-socketio#679]
the v1.7.17 version, browser open some tabs to connect the server，but the session id is same， and socketServer.getAllClients(), result always only 1,
but, the v1.7.7 is ok

**Comment by ellavas** [comment]
I have the same issue with the 1.7.17, version 1.7.12 is ok, why did you close this issue ?

**Comment by pangao66** [comment]
I have the same issue 1.7.18 ,version 1.7.12 is ok
