### ISSUE TITLE
SSL Error - net::ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by recon88** [mrniko/netty-socketio#729]
I have setup a keystore containing my Let's Encrypt cert which is being issued for the domain I'm using.

Server:
```
config.setKeyStorePassword("changeit");
InputStream stream = SslChatLauncher.class.getResourceAsStream("keystore.jks");
config.setKeyStore(stream);
```

Client:
```
socket = io.connect('https://xxx.xx:9443',{secure: true});
```
or
```
socket = io.connect('https://xxx.xx:9443');
```

Keystore (create and import Let's Encrypt cert):
```
keytool -genkey -alias chat -keyalg RSA -keystore keystore.jks -keysize 2048 -deststoretype PKCS12
keytool -import -alias chatcert -file /etc/ssl/xxx.xx/fullchain.pem  -keystore keystore.jks
```

Server starts fine, no errors but client is unable to connect
```
socket.io.js:2 GET https://xxx.xx:9443/socket.io/?EIO=3&transport=polling&t=1577624996333-0 net::ERR_SSL_PROTOCOL_ERROR
```
What am I doing wrong?

**Comment by pablojr** [comment]
1. You need to get more detailed logging both on the server and/or the client to see what's really going on.

My bet is that somehow client and server cannot agree on the version of the protocol to use (i.e. TLS 1.0 or 1.1 or 1.2 etc)

**Comment by recon88** [comment]
I was just dumb and didn't include the keystore in the app itself but put it in the folder where the app is running

**Comment by xujingzhou** [comment]
me too(I use .jks cert). could you ask me that how to solve this issue?

**Comment by sybcheck** [comment]
answer？
