### ISSUE TITLE
Pipeline customization methods are needed

### ISSUE THREAD

**Issue by ntrp** [mrniko/netty-socketio#73]
I noticed that the pipeline customization methods that were available in 1.0.5 now have been removed in 1.5.0. This methods should be available because without them the developer looses a lot of power. I wanted to append a static resource handler to serve my gui html files but it seems that it's not possible without modifing your code. Is there a way to do that with the 1.5.0 version?

**Comment by boyddddd** [comment]
@ntrp 
Hi, what you are doing is the same I need.
Could you share how to implement the HttpServerHandler?

**Comment by ntrp** [comment]
Took me some time to remember which project was it about 😂.
https://bitbucket.org/ntrp/ums-web-interface/src/master/src/main/java/org/qantic/umsplugin/HttpStaticFileServerHandler.java

**Comment by boyddddd** [comment]
> Took me some time to remember which project was it about 😂.
> https://bitbucket.org/ntrp/ums-web-interface/src/master/src/main/java/org/qantic/umsplugin/HttpStaticFileServerHandler.java

5 year-old project!!
Many thanks!!!
