### ISSUE TITLE
c.c.socketio.handler.InPacketHandler     : Error during data processing. Client sessionId: 9244fe37-6de4-4494-bfb9-ac5705ddfcfd, data: :42["messageevent","你好，你在哪里?"]

### ISSUE THREAD

**Issue by wangx1123-aaa** [mrniko/netty-socketio#732]
I use ie 9 send chinese word to server, then the server error,  ie 10 and ie 11 and chrome  is ok。the same client code, I do not know why。
![QQ图片20200117093854](https://user-images.githubusercontent.com/57558645/72577303-384ab680-390d-11ea-86e2-f1038ab8321c.png)

**Comment by wangx1123-aaa** [comment]
![pi](https://user-images.githubusercontent.com/57558645/72578213-6382d500-3910-11ea-8852-5cbc03f99e3b.png)

**Comment by mrniko** [comment]
ie 9 is not supported
