### ISSUE TITLE
Add CORS headers to server

### ISSUE THREAD

**Issue by Martijnpold** [mrniko/netty-socketio#749]
Currently our Angular based project is failing to connect to our java socket-io backend. As far as we can see this happens due to the browser rejecting the connection because of an invalid CORS header.

How do you configure these headers to be correct and allow any connection from any IP?

We tried:
config.setOrigin("*");
config.setOrigin("[full ip]");
config.setOrigin("[full ip]:*");
and various mutations similar, none seem to work though

**Comment by pim97** [comment]
Could you try this

config.setOrigin("*");

It adds a wildcard to the 'Access-Control-Allow-Origin' header

**Comment by voonic** [comment]
> Could you try this
> 
> config.setOrigin("*");
> 
> It adds a wildcard to the 'Access-Control-Allow-Origin' header

does not work

**Comment by BenanaH** [comment]
I have a same probelem.Is there something way to solve this?

**Comment by yujuncai** [comment]
config.setAllowHeaders("*");

**Comment by Martijnpold** [comment]
Old post but I believe this can also be solved by using the angular proxy configuration (partially an assumption, but I've had similar things with rest api's in dev environments).

More here: https://angular.io/guide/build#proxying-to-a-backend-server

Will close this issue and good luck to anyone reading this.
