### ISSUE TITLE
How to customize the default URL(/socket.io/?EIO=...) in client and server?

### ISSUE THREAD

**Issue by Tracy0725** [mrniko/netty-socketio#801]
I want to customize the URL such as /mySockketIO/?EIO=...

**Comment by wang271724646** [comment]
Server Options has a context attribute

**Comment by Tracy0725** [comment]
Thanks! I have found it.
In client:
 IO.Options options = new IO.Options();
options.path = "/subscribe.socket.io";
In cerver:
com.corundumstudio.socketio.Configuration config = new com.corundumstudio.socketio.Configuration();
config.setContext("/custom.socket.io");

**Comment by gurkanucar** [comment]
@Tracy0725 thanks a lot!

**Comment by AleksandarTokarev** [comment]
This context works properly and it sets up the context for handshake - but for actually sending the messages it does not work. Any idea how this can be done?
