### ISSUE TITLE
Does the latest 1.7.19 version support SockeTiO 3.x /4.x?

### ISSUE THREAD

**Issue by xujingzhou** [mrniko/netty-socketio#805]
Which version of the 1.7.19 version supports native Socketio? e.g. 2.x / 3.x /4.x

Error beased android:
 io.socket.client.SocketIOException: It seems you are trying to reach a Socket.IO server in v2.x with a v3.x client, which is not possible

**Comment by welkinbai** [comment]
Same problem. seem just support 2.x ……

**Comment by dcbarans** [comment]
Would also love to know if there are plans to support 3.x+ moving forward.  There are many optimizations and improvements I want to take advantage of on the client side.

**Comment by JanCizmar** [comment]
+1

**Comment by kingrockw** [comment]
+1

**Comment by tanksphere** [comment]
https://github.com/mrniko/netty-socketio/compare/master...tanksphere:netty-socketio:master

**Comment by mrniko** [comment]
it's now supported https://github.com/mrniko/netty-socketio/pull/897
