### ISSUE TITLE
which version of socket.io.js should I use for netty-socketio 1.7.19?

### ISSUE THREAD

**Issue by jmbkeyes** [mrniko/netty-socketio#809]
I tested 4.x,3.x version,  and found that  client could connect to server, but server  couldn't receive message from client and client couldn't receive message from server.
which version of socket.io.js should I use for netty-socketio 1.7.19?

**Comment by lliuhaomin** [comment]
2.x

**Comment by jmbkeyes** [comment]
Thanks for  your reply.  I Hope that netty-socketio server can support latest version of socketio client.
