### ISSUE TITLE
socket.io.js(3.x,4.x) can't interact with servesocketio server(netty-socketio)

### ISSUE THREAD

**Issue by jmbkeyes** [mrniko/netty-socketio#810]
I start netty-socketio server, try to use socket.io.js(3.x,4.x) to connect the server. The connection is established between client and server, but amazing things has happened as follows.

1. server received two connection events.
2. server can't receive message from client, and client can't receive message from server.

But when I downgrade to version under version 3.0(e.g. 2.4.0), all things works as excepted.

**Comment by mrniko** [comment]
fixed in https://github.com/mrniko/netty-socketio/pull/897
