### ISSUE TITLE
Do you know any v3 or higher server?

### ISSUE THREAD

**Issue by ErsinDemirbas** [mrniko/netty-socketio#814]
Hello sir, I am an jr.Android Developer and created a socket.io client side with java. So I think you know there is v1 or v2 in client side for java. My problem is that my company use v3 in server side so I have to use v2 client (highest version in java) but I cant connect to their server. So I need to a v3 or higher server side url for test my client side for check the problem is in my side or in server side. Do you know any v3 or higher server?

Note: When I switch to v1 in client I can easly connect to other v2 servers.

**Comment by ShirasawaSama** [comment]
The official website of socket.io has the link you want. You can check the network connection of the webpage.

I also encountered your problem, so I developed a new version of the server, but the client is still writing.

**Comment by ErsinDemirbas** [comment]
> The official website of socket.io has the link you want. You can check the network connection of the webpage.

Thanks a lot for your response. I knew about 2 demos in socket.io before.

https://socketio-chat-h9jt.herokuapp.com/
https://socketio-whiteboard-zmx4.herokuapp.com/

But I know they are not v3 and above. You can even check it from this website https://amritb.github.io/socketio-client-tool/ , while there is no connection in v3 and above section, there is a connection in v2 section in that page. So I think these are not v3 and above servers.

**Comment by mrniko** [comment]
4.0 is now supported https://github.com/mrniko/netty-socketio/pull/897
