### ISSUE TITLE
Max connections

### ISSUE THREAD

**Issue by SudoDios** [mrniko/netty-socketio#818]
My question is how many people does this library have the power to support in chat?  Depends on server power?

**Comment by mrniko** [comment]
yes

**Comment by jmbkeyes** [comment]
@mrniko  I started one socket server and  tested in my local windows machine(cpu i78700, mem 40G). And I found that  new connection can't be established after about 31000 connections.  

I also did test in centos7 with 2C8G, connection can't be established after about 31000 connections.  

Do I need to modify some configurations?

**Comment by SudoDios** [comment]
That means you have to build a new server?

**Comment by jmbkeyes** [comment]
@asd375zxcvb I  remember that I don't do extra configuration, just use Jmeber with websocket plugin to establish connections.

**Comment by yujuncai** [comment]
you can refer to it      https://socket.io/docs/v4/performance-tuning/ 
There are tuning instructions here    @asd375zxcvb @SudoDios @jmbkeyes

**Comment by yujuncai** [comment]
@SudoDios 
If it's helpful to you, please give a mark

**Comment by SudoDios** [comment]
This issue has been resolved for a long time.
I forgot to close this issue

**Comment by dannyZhou** [comment]
> @jmbkeyes Why is my socket.io service only able to support 64 client connections? I am using the default configuration, and this is the case both on the server and on my local computer. The server configuration is 4 CPUs and 8 GB of RAM. how did you configure the maximum number of connections?

https://github.com/mrniko/netty-socketio/issues/980#issuecomment-2101965684

Maybe it can helps you.
