### ISSUE TITLE
Does NettySocketio support bidirectional authentication?

### ISSUE THREAD

**Issue by xujingzhou** [mrniko/netty-socketio#824]
Does NettySocketio support bidirectional authentication? How do I do it?

**Comment by xujingzhou** [comment]
请问，netty-socketio目前支持双向认证么？ 如果支持应该怎么编码？ 如果不支持有没有计划什么版本/时候能支持？ thanks.

**Comment by unverbraucht** [comment]
Recent changes implement the auth token functionality of socket.io v4.
