### ISSUE TITLE
Will  this library support socket.o v3/v4

### ISSUE THREAD

**Issue by masa2146** [mrniko/netty-socketio#831]
I have angular 11 project and I use socket.io. But I have to use socket.io v3 and newer because Angular 11 doesn't support v2.x.
I used this library in backend. But this project doesn't support socket.io 3.x or newer. Accoring to me other guys want it to support v3/v4.

**Comment by mrniko** [comment]
There is no plans to implement support for protocol v3/v4 implementation.

**Comment by pbadenski** [comment]
Could you elaborate? Is this due to lack of capacity or technical limitations?

**Comment by mrniko** [comment]
4.0 is now supported https://github.com/mrniko/netty-socketio/pull/897
