### ISSUE TITLE
 Is there a plan to support v3/v4 in the next version?

### ISSUE THREAD

**Issue by dingshaohua-cn** [mrniko/netty-socketio#832]
v2.x has many inconveniences, such as not supporting `esm` and `vite`.   
The new version certainly has better performance.   
By default, `npm`，`yarn`，`pnpm` installs the latest cli version. 
Otherwise, the version should be specially declared

**Comment by mrniko** [comment]
There is no plans to implement support for protocol v3/v4 implementation.

**Comment by Bistuer** [comment]
i have same question

**Comment by mrniko** [comment]
4.0 is now supported https://github.com/mrniko/netty-socketio/pull/897
