### ISSUE TITLE
Is this repository still keeping update to `socket.io`?

### ISSUE THREAD

**Issue by ruojianll** [mrniko/netty-socketio#834]
The last commit is on May 24. Is this repository still keeping update to `socket.io`'s latest version?

**Comment by mrniko** [comment]
It doesn't support latest version.

**Comment by kgecici** [comment]
It works very well with 1.x official java client. It can be great to support 2.x

**Comment by mrniko** [comment]
4.0 is now supported https://github.com/mrniko/netty-socketio/pull/897
