### ISSUE TITLE
about socket.io version

### ISSUE THREAD

**Issue by webinone** [mrniko/netty-socketio#835]
Currently, I know that socket.io 3/4 is not supported.
I'm using netty-socketio to process a lot of data in real time. I really appreciate it.
However, as others are talking about the issue, I feel the need to upgrade socket.io.
However, after seeing the reply that there was no plan, I wonder if there was really no plan to upgrade the version.
Or I am wondering if it is possible to proceed with socket.io version 3/4 with a pull request.

**Comment by Bistuer** [comment]
i have same question

**Comment by mrniko** [comment]
I'm ready to consider PR related to this task

**Comment by mrniko** [comment]
4.0 is now supported
