### ISSUE TITLE
Memory problem Please help me

### ISSUE THREAD

**Issue by webinone** [mrniko/netty-socketio#841]
I am using version 17.19, and the site has been opened. The number of concurrent users is approximately 20,000.
And I am using redisson too. (3.16.7)
Two NameSpaces are in use.
However, I noticed that the memory gradually increased,
I checked my source, but couldn't figure out the cause.
In the end, I deleted all the logic of the source code, and at the end, only the logic to connect to socket io was left.
The user is in a situation where only connect, disconnect, joinRoom, and leaveRoom are continuously being made and no other actions can be performed. However, the memory is still increasing little by little.
It's very likely my problem, but I was wondering if anyone is experiencing the same memory leak as me.
Whether a memory leak occurs simply through connect and disconnect.
Please help me.

**Comment by janyyy** [comment]
Has the problem been solved?

**Comment by webinone** [comment]
@janyyy 
I have been running netty socketio for about 7 months now.
I was worried a lot. The problem was that the RSS Memory increased, and I checked the memory dump countless times.
I suspected a native memory leak.
But now it seems that the memory problem has been solved. It's hard to tell in detail

The issues here did not occur to me.
https://github.com/mrniko/netty-socketio/issues/829

Please refer to this issue.
https://github.com/mrniko/netty-socketio/issues/415

Good Luck!
