### ISSUE TITLE
New version release?

### ISSUE THREAD

**Issue by webinone** [mrniko/netty-socketio#853]
When will the new version be released? It seems like a lot of commits have been merged.

**Comment by mrniko** [comment]
Done

**Comment by webinone** [comment]
@mrniko how can i mvn dependency

<dependency>
 <groupId>com.corundumstudio.socketio</groupId>
 <artifactId>netty-socketio</artifactId>
 <version>1.7.20</version>
</dependency>

**Comment by mrniko** [comment]
Please try again
