### ISSUE TITLE
1.7.20 version error

### ISSUE THREAD

**Issue by webinone** [mrniko/netty-socketio#854]
I have been using netty-socketio since 2 years ago, and I am currently running version 1.7.19.
 
A new version #853
`implementation group: 'com.corundumstudio.socketio', name: 'netty-socketio', version: '1.7.20'`

However, at the same time as setting, clients cannot connect. The error contents are as follows.

com.corundumstudio.socketio.handler.AuthorizeHandler","message":"Unknown transport for request /socket.io/?EIO=3&token={token}&transport=websocket"}

Of course it works fine with 1.7.19 There seems to be a problem with the new version (1.7.20).

@mrniko

**Comment by webinone** [comment]
There seems to be a problem with this pr. #808 
If you want to do it that way, you need to make sure the transport is all uppercase.

ex) /socket.io/?EIO=3&token={token}&transport=websocket-> error
/socket.io/?EIO=3&token={token}&transport=WEBSOCKET -> ok

I will fix it through a pull request.

**Comment by hiredman** [comment]
1.7.20 is a very broken release.

1. https://github.com/mrniko/netty-socketio/blob/fe5368e9625edd4b1f5b0e1c61d75de4d3fdd9a3/src/main/java/com/corundumstudio/socketio/handler/AuthorizeHandler.java#L184 requires the transport name be upper case, `WEBSOCKET` or `POLLING`
2. https://github.com/mrniko/netty-socketio/blob/fe5368e9625edd4b1f5b0e1c61d75de4d3fdd9a3/src/main/java/com/corundumstudio/socketio/transport/PollingTransport.java#L68 requires the transport name to be `polling`
3. clients all send `websocket` or `polling` by default.

#1 and #2 mean the polling transport is completely broken. 
#3 means clients that worked fine with the previous patch release break with with this new patch release.

To make 1.7.20 work I have to add a pipeline handler before AUTHORIZE_HANDLER which upper cases the value of the `transport` query parameter, and another pipeline handler before XHR_POLLING_TRANSPORT which lower cases the value of `transport`.

**Comment by mrniko** [comment]
Fixed in https://github.com/mrniko/netty-socketio/commit/206f33006befaedfe47153a42ea2b4c7bfe301ee
