### ISSUE TITLE
Which client version is supported?

### ISSUE THREAD

**Issue by KevinAtlans** [mrniko/netty-socketio#864]
`<dependency>`
    `<groupId>com.corundumstudio.socketio</groupId>`
    `<artifactId>netty-socketio</artifactId>`
    `<version>1.7.22</version>`
`</dependency>`

Which client version does the server 1.7.22 support at most?

"socket.io-client": "^2.5.0" ？
"socket.io-client": "^3.1.3" ？
"socket.io-client": "^4.5.2" ？

I can only use 2.5.0

Can 4.5.2 be used? Can you give me an example if you can?

Pls tell me. Thx

**Comment by chlp1055378613** [comment]
顶

**Comment by HashZhang** [comment]
If you don't care about the minor encoding mechanism for binary body, you can git it a try now using the latest version of socketio client. I only fix the reversing of ping/pong mechanism: https://github.com/mrniko/netty-socketio/pull/858

**Comment by chlp1055378613** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jptangchina** [comment]
I have the same question too. And I've tried to use the latest socket.io-client 4.5.2 but then I got this error from the "connect_error" event: It seems you are trying to reach a Socket.IO server in v2.x with a v3.x client, but they are not compatible (more information here: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/).
Please let me known if you have the solution.

**Comment by akshayrpatel** [comment]
I have the same problem, not able to connect using `socket.io-client` `v3.x` or `v4.x`, but seems to work with `v2.x`

**Comment by BanDaosc** [comment]
I have the same problem. using the latest api and still not support client v3&4
![image](https://user-images.githubusercontent.com/43674672/197141170-63824258-5405-47cf-bab6-a61a71dc6d68.png)

**Comment by yisuren** [comment]
It seems we can only use socketio 2.x version for out client. It really sucks and frustrats me.

**Comment by mrniko** [comment]
At the moment only 2.x version is supported

**Comment by rfermontero** [comment]
Any plans to support newer versions @mrniko? Or do we have at least which changes are required to?

**Comment by faizanhaidarkhan** [comment]
1.0.1 and 1.0.2 java clients are compatible with 1.7.22

**Comment by mrniko** [comment]
@rfermontero 

Sorry, no plans so far.

**Comment by ZhouShengEn** [comment]
> 1.0.1 和 1.0.2 java 客户端与 1.7.22 兼容，但此服务器存在断开连接问题。服务器 1.7.8 目前运行良好。



> Any plans to support newer versions @mrniko? Or do we have at least which changes are required to?

you can try to change transport to websocket

**Comment by kevinfubei** [comment]
在 com/corundumstudio/socketio/protocol/PacketEncoder.java:298 位置加一个sid的json字符串即可解决客户端这个报错：
connect_error Error: It seems you are trying to reach a Socket.IO server in v2.x with a v3.x client, but they are not compatible

**Comment by mrniko** [comment]
4.0 https://github.com/mrniko/netty-socketio/pull/897
