### ISSUE TITLE
auto disconnected after update to 1.7.22

### ISSUE THREAD

**Issue by jptangchina** [mrniko/netty-socketio#866]
I'm not sure if this is a bug. With server 1.7.22, and socket.io-client 2.5.0, the server auto disconnect with client because of ping timeout.(this works fine with server version 1.7.21)

Also this can be reproduce on your demo project:
![image](https://user-images.githubusercontent.com/32792872/193008163-641f49f3-51fa-4745-a335-32c08f201e82.png)

BTW: It says that 1.7.22 supports for the v4 ping/pong mechanism, is that means I can use socket.io-client 4.x? I'v tried so but I got this error:  It seems you are trying to reach a Socket.IO server in v2.x with a v3.x client, but they are not compatible (more information here: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/)

**Comment by haiyiya** [comment]
I met the same problem.

**Comment by moritzhabegger** [comment]
That confused me also, I also thought this library only supports socket.io v2. It seems like 1.7.22 broke the ping/pong support for 2.5.0 (socket.io-client) and that is causing the reconnect. With version 1.7.20 and 1.7.21 I get `Unknown transport for request /socket.io/?EIO=3&transport=websocket` on the server side. 
The combination of 1.7.19 (netty-socketio) and 2.5.0 (socket.io-client) is working fine for me.

**Comment by kang0821** [comment]
me too,  will resovle this problem in v1.7.23 ?

**Comment by JiangYongKang** [comment]
@moritzhabegger  Me too, But after I rolled back to 1.7.19 everything works fine.

**Comment by yujuncai** [comment]
me too,   rolled back to 1.7.21.....will be normal

**Comment by DavidAttar** [comment]
Does anyone know why they implemented v4 ping/pong support when it says in the readme that they support v2 clients?

**Comment by mrniko** [comment]
Can you try version attached?

[netty-socketio-1.7.23-SNAPSHOT.jar.zip](https://github.com/mrniko/netty-socketio/files/10553816/netty-socketio-1.7.23-SNAPSHOT.jar.zip)

**Comment by yujuncai** [comment]
![image](https://user-images.githubusercontent.com/9441501/215993246-f70d7159-40cb-4b6a-8a58-d6fb1d0f750a.png)
![image](https://user-images.githubusercontent.com/9441501/215993409-2b4e20e7-4d37-424b-bf46-4c279112c91c.png)
I just replaced jar to 1.7.23......A lot of netty's class are missing

**Comment by mrniko** [comment]
you need to copy netty libs from pom.xml since dep defined as a file.

**Comment by yujuncai** [comment]
eeeee.......I  replaced jar to 1.7.23....auto disconnected  never appeared again

**Comment by mrniko** [comment]
Fixed! Thanks for testing

**Comment by mrniko** [comment]
1.7.23 version has been released
