### ISSUE TITLE
Possible memory leak in 1.7.22?

### ISSUE THREAD

**Issue by seancorfield** [mrniko/netty-socketio#868]
We just updated from 1.7.21 to 1.7.22 and saw a steady rise in memory usage that GC could not recover, across all of our servers. We reverted to 1.7.21 (the only change) and memory usage remained stable, as it was before the update. We haven't had a chance to look at a heap dump yet (we had to revert as an emergency over the weekend) but wanted to get it on your radar.

I looked over the diffs from 1.7.21 to 1.7.22 and didn't see any smoking gun, in terms of changes that might cause this. We'll try to take a deeper look this week if we can schedule that investigate around other work.

**Comment by hiredman** [comment]
https://github.com/mrniko/netty-socketio/compare/netty-socketio-1.7.21..master#diff-8aedd92990cfbafdc292f21882a27dea90efd28afae56a69c3816b8f79090813R136

seems like it could be the leak.

schedulePing schedules a Runnable, and that Runnable unconditionally calls schedulePing again, even if the session is no longer in the clientsBox.

**Comment by hiredman** [comment]
the way the new ping/pong stuff is implemented, for every PONG message from a client, a new timeout "loop" is started. I think if a client just sent PONGs in a loop, even without the leak in schedulePing, you could oom the server.

ideally a client would be limited to a single timeout for pings at a time

**Comment by mrniko** [comment]
Fixed! Thanks for report
