### ISSUE TITLE
How to set the key written by the redissonclient to have an expiration time

### ISSUE THREAD

**Issue by yujuncai** [mrniko/netty-socketio#878]
` config.setStoreFactory(new RedissonStoreFactory(redissonClient));`
when
`client.set(USER_KEY, user);  `
The expiration time cannot be set

**Comment by mrniko** [comment]
You can extend RedissonStoreFactory and RedissonStore to use RMapCache object instead

**Comment by sandalovsergey** [comment]
@mrniko please see similar issue #982
