### ISSUE TITLE
一个socketIOServer创建多个Namespace，前端怎么连接

### ISSUE THREAD

**Issue by fengsam6** [mrniko/netty-socketio#888]
@Bean
    public SocketIOServer socketIOServer() {
        SocketConfig socketConfig = new SocketConfig();
        socketConfig.setTcpNoDelay(true);
        socketConfig.setSoLinger(0);
        com.corundumstudio.socketio.Configuration config = initSocketConfig();
        config.setSocketConfig(socketConfig);
        config.setHostname("0.0.0.0");
        config.setPort(socketIOProperties.getPort());
        config.setExceptionListener(socketExceptionListenerAdapter);
        SocketIOServer socketIOServer = new SocketIOServer(config);
        List<String> namespaces= getAppInitNamespace();
        namespaces.forEach(socketIOServer::addNamespace);
        return socketIOServer;
    }

    /**
     * 可以从配置文件，配置中心获取
     * @return
     */
    private List<String> getAppInitNamespace() {
        return Arrays.asList("/scroom.websocket","/exam.websocket","/socket.io");
    }

// 建立连接
			//wss://school-test.ybccode.com/ada-scroom-python/terminal/"+token
			var token =
				'eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhZGEtc2Nyb29tIiwic3ViIjoie1widXNlcklkXCI6MjEsXCJ0ZW5hbnRJZFwiOjEsXCJvcGVuSWRcIjowLFwidW5pb25JZFwiOjIyMixcInJvbGVcIjpcInN0dWRlbnRcIixcImV4cGlyZVRpbWVcIjowLFwic291cmNlXCI6XCJ5a3RcIixcImF1dGhQbGF0Zm9ybVwiOlwieWt0XCIsXCJzc29Mb2dpblwiOjB9IiwiaWF0IjoxNjgxNzIwOTAxfQ.L0CCFRug8WVFjuKE9M2RHcGMqoRh1CTZMCAYmYLtrZ4'
			var socket = io('http://127.0.0.1:8080/exam.websocket?authorToken=' + token, {
				// path: '/exam.websocket',
				transports: ["websocket"]
			});
			// 监听 message 会话
			socket.on('*', function(data) {
				let html = document.createElement('p')
				html.innerHTML = `系统消息：<span>${data.hello}</span>`
				document.getElementById('content').appendChild(html)
				console.log(data);
			});

**Comment by Miaomz** [comment]
Could you provide more details on what you encountered? By the way, I think '/socket.io' is not a good namespace.

**Comment by Miaomz** [comment]
If the path of your socket.io server is '/ada-scroom-python/terminal/{token}', I guess the request should be something like

var socket = io('http://127.0.0.1:8080/exam.websocket', {
query: {
    authorToken: token,
},
path: `/ada-scroom-python/terminal/${token}`,
transports: ["websocket"]
});

**Comment by fengsam6** [comment]
ok，thanks，I try it.
