### ISSUE TITLE
How can I support 3.x+ version of Socket.IO-client

### ISSUE THREAD

**Issue by wysstartgo** [mrniko/netty-socketio#894]
Is there any plan to support 3.x+ version of Socket.IO-client? I want to do some contribute.

**Comment by charliejinc** [comment]
I have the same problem

**Comment by mrniko** [comment]
support of this version isn't planned

**Comment by charliejinc** [comment]
Is there any plan to support 4.x+ version of Socket.IO-client?

**Comment by mrniko** [comment]
Done https://github.com/mrniko/netty-socketio/pull/897
