### ISSUE TITLE
Clients (JS, Postman) cannot connect to namespace

### ISSUE THREAD

**Issue by mvandermade** [mrniko/netty-socketio#901]
Hi,
I was following along the sample project for namespaces (https://github.com/mrniko/netty-socketio-demo/blob/master/server/src/main/java/com/corundumstudio/socketio/demo/NamespaceChatLauncher.java).
Unfortunately my clients (Postman & Javascript socket-io-client) cannot get a proper connection state.

I can see in the console log of the browser that indeed a websocket is set-up and that data transfers, but the connected state stays "false":
<img width="309" alt="image" src="https://github.com/mrniko/netty-socketio/assets/33425497/0b99f700-d968-4ad1-ab96-0aece7af2b53">

<img width="1647" alt="image" src="https://github.com/mrniko/netty-socketio/assets/33425497/7e838fb1-bcaf-449d-98cd-db4fe1b884c3">
And the second socket:
<img width="1647" alt="image" src="https://github.com/mrniko/netty-socketio/assets/33425497/0d534673-7660-4b76-9377-c1692917c086">

Postman client just keeps the orange indicator that it is connecting:
<img width="883" alt="image" src="https://github.com/mrniko/netty-socketio/assets/33425497/d6ee71ce-28b6-46db-9ce0-2b8f6d56a064">

I added some log statements to the server (```chat1namespace.addConnectListener((client -> System.out.println("Client connected to namespace 1")));```) Which trigger.

When I connect to the server without a namespace it works:
<img width="883" alt="image" src="https://github.com/mrniko/netty-socketio/assets/33425497/70970f1e-252e-4bb7-85cf-4e68c5bb809b">

Any advice how to proceed?

Thanks for checking out the issue!

-- Dev environment detais ---
Java, Gradle, running the main file as in the example mentioned above but with version com.corundumstudio.socketio:netty-socketio:2.0.2
Vite + Typescript + React + Socket.io client (https://socket.io/how-to/use-with-react)
Postman Socket IO option (I believe this is using V4 of the protocol)

**Comment by mvandermade** [comment]
As commented the client does work at v2. Closes the issue because it works with v2!

**Comment by mrniko** [comment]
@HashZhang

Can you check that?

**Comment by lyjnew** [comment]
我修补它 https://github.com/lyjnew/netty-socketio-patch

**Comment by lyjnew** [comment]
![image](https://github.com/mrniko/netty-socketio/assets/7028443/c9433c02-d58c-489b-b001-09f29b4e32f3)

**Comment by mrniko** [comment]
fixed
