### ISSUE TITLE
Compatibility with client version v3, v4 when using namespace

### ISSUE THREAD

**Issue by shoukou-lee** [mrniko/netty-socketio#908]
### netty-socketio version
- 2.0.2

When I run [this demo](https://github.com/mrniko/netty-socketio-demo/blob/master/server/src/main/java/com/corundumstudio/socketio/demo/NamespaceChatLauncher.java), the client connection works fine with the html provided.

However, when I try to connect to the server using Postman, the connection fails after waiting for a few seconds in the `Connecting` state. The picture below shows a stuck state when trying to connect via the **socket.io client version v3/v4.**
![image](https://github.com/mrniko/netty-socketio/assets/74892010/45aa4ab0-1432-495c-8767-11d45580d2c3)

However, if the client version is set to v2, the connection works fine using Postman, like below.
![image](https://github.com/mrniko/netty-socketio/assets/74892010/3fece704-7c39-4351-bba9-363501ad602b)

Note that I ran this demo with netty-socket.io v2.0.2. Also I read in this [release note](https://github.com/mrniko/netty-socketio/releases/tag/netty-socketio-2.0.0) that Socket.IO v4.x is supported.

If I join the default namespace, it connects just fine with v3 and v4. This issue seems to happen with clients joining the namespace.

**Comment by LeCarteloo** [comment]
I am using Socket.IO v4 on my client, but despite the release notes suggesting compatibility with v4, it only functions properly with v2. This is quite disappointing as v2 does not support TypeScript. I tried alot stuff but nothing seems to work. When using the Node.js implementation, it performs flawlessly.

**Comment by docukl** [comment]
I also encountered the same problem.

**Comment by ligaowu** [comment]
same problem

**Comment by lyjnew** [comment]
V4 web socket connct have some error   ,send  open packet  no naspace

**Comment by lyjnew** [comment]
![image](https://github.com/mrniko/netty-socketio/assets/7028443/c9433c02-d58c-489b-b001-09f29b4e32f3)

**Comment by AfaqaL** [comment]
@lyjnew postman shows an error when connecting, saying that server is of version 2.x, how do I configure the server to accept v4 connections?

**Comment by lyjnew** [comment]
update you jar to 2.0.2,default super V2,V3,V4,  run this demo 
https://github.com/mrniko/netty-socketio-demo/blob/master/server/src/main/java/com/corundumstudio/socketio/demo/NamespaceChatLauncher.java

**Comment by cnlinjie** [comment]
same problem

**Comment by shutuper** [comment]
same problem

**Comment by mrniko** [comment]
fixed
