### ISSUE TITLE
CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by emoahg** [mrniko/netty-socketio#916]
com.corundumstudio.socketio.Configuration configuration = new com.corundumstudio.socketio.Configuration();
configuration.setHostname(hostname);
configuration.setPort(port);
configuration.setOrigin("\*");
configuration.setAllowHeaders("\*");
SocketIOServer socketIOServer = new SocketIOServer(configuration);
socketIOServer.start();

still cross domain issues, help

**Comment by emoahg** [comment]
configuration.setOrigin("*");
configuration.setAllowHeaders("*");

**Comment by 6LWa6ZKx** [comment]
遇到了一样的问题，请问如何处理

**Comment by emoahg** [comment]
> com.corundumstudio.socketio.Configuration configuration = new com.corundumstudio.socketio.Configuration(); configuration.setHostname(hostname); configuration.setPort(port); configuration.setOrigin("*"); configuration.setAllowHeaders("*"); SocketIOServer socketIOServer = new SocketIOServer(configuration); socketIOServer.start();
> 
> still cross domain issues, help

不使用 *，
对于放开的网站使用逗号分隔，类如：configuration.setOrigin("https://abc.com,https://def.com");
对于自定义的请求头里面的信息也要声明，类如：configuration.setAllowHeaders("auth,language");
我是这样解决的。
我使用的是 2.0.3 版本。

**Comment by 6LWa6ZKx** [comment]
> > com.corundumstudio.socketio.Configuration configuration = new com.corundumstudio.socketio.Configuration(); configuration.setHostname(hostname); configuration.setPort(port); configuration.setOrigin("_"); configuration.setAllowHeaders("_"); SocketIOServer socketIOServer = new SocketIOServer(configuration); socketIOServer.start();
> > still cross domain issues, help
> 
> 不使用 *， 对于放开的网站使用逗号分隔，类如：configuration.setOrigin("https://abc.com,https://def.com"); 对于自定义的请求头里面的信息也要声明，类如：configuration.setAllowHeaders("auth,language"); 我是这样解决的。 我使用的是 2.0.3 版本。

谢谢，我强制ws，不用http形式，这样解决了。现在是namespace无法加入。
