### ISSUE TITLE
I have to wait 20 seconds before restarting my java spring boot app because of SocketIO

### ISSUE THREAD

**Issue by MilanObrenovic** [mrniko/netty-socketio#920]
when i restart the spring boot app it cant start because socketio is still listening on port e.g. 9000. i need to wait 20 seconds till i can restart the app again. how to fix this? whats the proper way to shut down socketio server and flush all from memory when the app dies or gets shut down?

this is how i close it:

```java
@PreDestroy
public void close() {
    socketIOServer.stop();
}
```

**Comment by shutuper** [comment]
Set reuseAddress to true inside SocketConfig

**Comment by MilanObrenovic** [comment]
> Set `reuseAddress` to `true` inside `SocketConfig` (`Configuration.socketConfig`)

that method doesn't exist. I'm using socketIO 2.0, perhaps thats why?

**Comment by shutuper** [comment]
@MilanObrenovic It should be present

**Comment by MilanObrenovic** [comment]
> @MilanObrenovic It should be present <img alt="image" width="564" src="https://user-images.githubusercontent.com/70547118/260751835-77c22589-36fe-4337-a3dc-ac40f3fd8519.png">

no i dont have that method.


```java
@Slf4j
@Configuration
@AllArgsConstructor
public class SocketIOConfig {

    @Value("${socketIO.host}")
    private String socketIOHost;

    @Value("${socketIO.port}")
    private Integer socketIOPort;

    // ...

    @Bean
    public SocketIOServer socketIOServer() {
        com.corundumstudio.socketio.Configuration config = new com.corundumstudio.socketio.Configuration();
        config.setHostname(socketIOHost);
        config.setPort(socketIOPort);
        config.setAuthorizationListener(handleAuthorization());
        return new SocketIOServer(config);
    }

    // ...

}
```

![image](https://github.com/mrniko/netty-socketio/assets/56999235/51a976d3-7c4d-4273-a46c-b1add5ea8acc)

where is it?

**Comment by shutuper** [comment]
add `config.getSocketConfig().setReuseAddress(true);`...

**Comment by shutuper** [comment]
> > add `config.getSocketConfig().setReuseAddress(true);`...
> 
> thank you for clearing that up. you never mentioned it comes from `getSocketConfig()` method beforehand in your previous replies, so it was unclear where do you find it from.
> 
> this has now fixed the issue

You are welcome but I have also mentioned it earlier)
