### ISSUE TITLE
Memory Leak while WebSocketServerHandshakeException or Channel failed

### ISSUE THREAD

**Issue by HashJang** [mrniko/netty-socketio#925]
when there is WebSocketServerHandshakeException, such as "WebSocketServerHandshakeException: not a WebSocket request: a |Connection| header must includes a token 'Upgrade'" (missing Upgrade header in httprequest), there would be in memory leak in `uuid2clients`
![1690511235074](https://github.com/mrniko/netty-socketio/assets/15627489/8ad5faf3-eea2-4664-a064-94fa2d901f3e)

**Comment by webinone** [comment]
@HashZhang i have sample problem
