### ISSUE TITLE
if ack returns after the timeout trigger ,a IllegalStateException will be thrown

### ISSUE THREAD

**Issue by BianJianyu** [mrniko/netty-socketio#964]
version:2.0.9

1. onTimeout() will remove ackCallback，however ackCallback is necessary while package decoding.
file:com/corundumstudio/socketio/ack/AckManager.java line:157
<img width="1054" alt="image" src="https://github.com/mrniko/netty-socketio/assets/5669527/7893527a-4586-4e9d-b443-14d8704d3389">
file:com/corundumstudio/socketio/protocol/PacketDecoder.java line:300
<img width="1048" alt="image" src="https://github.com/mrniko/netty-socketio/assets/5669527/7a4c56c0-687e-45e8-8482-b479ef08786a">
2. if callback is null, the byteBuf   will not be read. And the the loop will run second time!
file:com/corundumstudio/socketio/handler/InPacketHandler.java line:64
<img width="1060" alt="image" src="https://github.com/mrniko/netty-socketio/assets/5669527/54813b61-505e-41b5-aff7-bccb4e3904a1">
3. however the data in the buffer is already wrong, so it cannot get the right type, and then throw the IllegalStateException
file:com/corundumstudio/socketio/protocol/PacketType.java line:42
<img width="673" alt="image" src="https://github.com/mrniko/netty-socketio/assets/5669527/4ff67e47-de80-4940-ba72-47999c89341e">

**Comment by malinGH** [comment]
if (callback != null) {
       ByteBufInputStream in = new ByteBufInputStream(frame);
       AckArgs args = jsonSupport.readAckArgs(in, callback);
       packet.setData(args.getArgs());
}else {
       frame.clear();
}
what if I write it like this？

**Comment by malinGH** [comment]
![3A6E8155-C3B6-41e6-BD11-3EAC9929600D](https://github.com/mrniko/netty-socketio/assets/40853744/df09a513-b46d-4dd2-87b4-3706d0cc6843)
![E853EA39-0E46-411E-83D0-1540D3F19ADE](https://github.com/mrniko/netty-socketio/assets/40853744/ad6986b5-0c52-4f4c-9908-2065344b385f)
this is test result

**Comment by mrniko** [comment]
@malinGH 

What about the case then there are other packets next to this packet? they won't be parsed if bytebuf readIndex reset to zero

**Comment by mrniko** [comment]
I think it's better to replace frame.clear with the code below.
```java
ByteBufInputStream in = new ByteBufInputStream(frame);
jsonSupport.readAckArgs(in, callback);
```

**Comment by mrniko** [comment]
It's better to use the code below.

```java
frame.readerIndex(frame.readableBytes());
```

Now the buffer was consumed completely.

**Comment by malinGH** [comment]
let me try

**Comment by malinGH** [comment]
![截屏2024-03-27 10 09 41](https://github.com/mrniko/netty-socketio/assets/40853744/d04a7e9b-376b-41de-b764-2b1da50d79e5)
<img width="931" alt="截屏2024-03-27 10 10 19" src="https://github.com/mrniko/netty-socketio/assets/40853744/4d192a24-10c7-4722-84c9-3475d585dcbd">
![6437A52C-EE5F-437a-B958-1BCE6E44AAAC](https://github.com/mrniko/netty-socketio/assets/40853744/cc866e3f-c9d9-4255-a3e5-22a0b1ce3ed4)

**Comment by malinGH** [comment]
@mrniko Test is fail, It's too bad. You need to test this version

**Comment by malinGH** [comment]
![截屏2024-03-27 15 57 26](https://github.com/mrniko/netty-socketio/assets/40853744/d749d56c-cfe6-4363-bd7d-fe1d40bcbd6b)

**Comment by malinGH** [comment]
![6437A52C-EE5F-437a-B958-1BCE6E44AAAC](https://github.com/mrniko/netty-socketio/assets/40853744/c3350813-6a63-4eb5-9618-dc6b9fe41176)

**Comment by mrniko** [comment]
merged
